/**
 * Nombres con los que la gente pide cada plato. Solo nombres inequívocos:
 * "lentejas" o "tortillas" son ingredientes, no peticiones de plato.
 */
export const DISH_KEYWORDS: Record<string, string[]> = {
  "tortilla-de-patatas": ["tortilla de patatas", "tortilla de patata", "tortilla espanola"],
  "pollo-al-ajillo": ["pollo al ajillo"],
  "lentejas-con-chorizo": ["lentejas con chorizo", "potaje de lentejas"],
  "garbanzos-con-espinacas": ["garbanzos con espinacas", "espinacas con garbanzos"],
  "pollo-al-horno-con-arroz": ["pollo al horno", "arroz al horno"],
  "gambas-al-ajillo": ["gambas al ajillo"],
  "merluza-al-horno-con-patatas": ["merluza al horno"],
  "huevos-rotos": ["huevos rotos", "huevos estrellados"],
  "sopa-de-ajo": ["sopa de ajo", "sopa castellana"],
  "pisto-con-huevo": ["pisto"],
  "fabada-asturiana": ["fabada"],
  "espaguetis-al-pomodoro": ["pomodoro", "espaguetis con tomate", "pasta con tomate"],
  carbonara: ["carbonara"],
  "arroz-frito-con-huevo": ["arroz frito", "arroz tres delicias"],
  "chilaquiles-rojos": ["chilaquiles"],
  quesadillas: ["quesadilla", "quesadillas"],
  guacamole: ["guacamole"],
  "tacos-de-pollo": ["taco", "tacos"],
  "pollo-al-curry": ["pollo al curry", "curry de pollo"],
  "dal-de-lentejas": ["dal"],
  karaage: ["karaage", "pollo frito japones"],
  oyakodon: ["oyakodon"],
  "choripan-chimichurri": ["choripan", "chimichurri"],
  "calamares-fritos-yogur": ["calamares fritos", "calamares a la romana", "rabas"],
  "panang-pollo": ["panang", "curry tailandes", "curry rojo"],
  "tallarines-verdes": ["tallarines verdes"],
  "ensalada-griega": ["ensalada griega"],
  "souvlaki-pollo-tzatziki": ["souvlaki", "tzatziki", "gyros"],
  "bibimbap-casero": ["bibimbap"],
  "chana-masala": ["chana masala"],
  "tajin-pollo-limon": ["tajin", "tagine"],
  "risotto-champinones": ["risotto", "rissotto"],
  "pasta-aglio-olio": ["aglio e olio", "aglio olio", "pasta al ajo"],
  shakshuka: ["shakshuka", "huevos con tomate"],
};
