/**
 * Más nombres con los que se pide cada plato (otros idiomas, nombres populares y
 * erratas habituales sin tildes). Mismo criterio: solo nombres inequívocos.
 */
export const DISH_KEYWORDS_2: Record<string, string[]> = {
  // España
  "cocido-madrileno": ["cocido madrileno", "puchero"],
  "pulpo-a-la-gallega": ["pulpo a feira", "pulpo gallego"],
  "croquetas-jamon": ["croquetas", "croquetas caseras"],
  salmorejo: ["salmorejo"],
  "ensaladilla-rusa": ["ensaladilla", "ensalada rusa"],
  "bacalao-pil-pil": ["pil pil", "pilpil", "bacalao al pilpil"],
  "merluza-salsa-verde": ["merluza en salsa verde", "merluza a la koskera"],
  fideua: ["fideua", "fideuada"],
  "arroz-al-horno": ["arros al forn"],
  migas: ["migas", "migas de pastor"],
  escalivada: ["escalivada", "escalibada"],
  "pan-con-tomate": ["pa amb tomaquet", "pan tumaca", "tostada con tomate"],
  "crema-catalana": ["crema catalana", "crema de sant josep"],
  torrijas: ["torrijas", "torrija"],
  porrusalda: ["porrusalda", "porrusalda de bacalao"],
  ajoblanco: ["ajoblanco", "ajo blanco"],
  "potaje-de-vigilia": ["potaje de vigilia", "potaje de garbanzos y bacalao"],
  "patatas-a-la-riojana": ["patatas con chorizo", "patatas a la riojana"],
  "pollo-en-pepitoria": ["pepitoria"],
  "berenjenas-con-miel": ["berenjenas con miel", "berenjenas fritas"],
  "ensalada-mixta": ["ensalada mixta", "ensalada verde"],
  "leche-frita": ["leche frita"],
  frixuelos: ["frixuelos", "fayuelos", "filloas", "crepes asturianos"],
  "merluza-a-la-sidra": ["merluza a la sidra"],
  "carne-gobernada": ["carne gobernada", "carne guisada asturiana"],
  "chorizo-a-la-sidra": ["chorizo a la sidra", "chorizo en sidra"],
  casadielles: ["casadielles", "casadiella"],
  "tarta-de-queso-vasca": ["tarta de queso", "tarta de queso de la vina", "cheesecake vasco"],
  natillas: ["natillas"],
  "crema-de-calabaza": ["crema de calabaza", "pure de calabaza"],
  "arroz-a-la-cubana": ["arroz a la cubana", "arroz con tomate y huevo"],
  "huevos-a-la-flamenca": ["huevos a la flamenca", "huevos al plato"],
  "calamares-encebollados": ["calamares encebollados", "calamares con cebolla"],
  "lomo-con-pimientos": ["lomo con pimientos", "pincho de lomo"],
  "pollo-al-chilindron": ["chilindron"],
  "caldereta-cordero": ["caldereta", "caldereta de cordero"],
  "cordero-asado": ["cordero asado", "cordero al horno", "pierna de cordero"],
  "huevos-rellenos": ["huevos rellenos", "huevos con atun"],
  "tortilla-calabacin": ["tortilla de calabacin"],
  "revuelto-champinones-jamon": ["revuelto de champinones", "revuelto de setas"],
  "mejillones-marinera": ["mejillones a la marinera", "mejillones en salsa"],
  "almejas-marinera": ["almejas a la marinera", "almejas en salsa"],
  "pollo-al-limon": ["pollo al limon al horno"],
  "lentejas-con-verduras": ["lentejas con verduras", "lentejas vegetarianas", "lentejas veganas"],
  "patatas-a-lo-pobre": ["patatas a lo pobre", "patatas panaderas"],
  "judias-verdes-con-patatas": ["judias verdes", "judias con patatas", "vainas con patatas"],
  "arroz-caldoso-marisco": ["arroz caldoso", "arroz meloso de marisco"],
  "fabes-con-almejas": ["fabes con almejas", "alubias con almejas"],
  "arroz-con-pitu": ["arroz con pitu", "arroz con pollo de corral"],
  "escalopines-cabrales": ["escalopines al cabrales", "salsa de cabrales"],
  "crema-de-calabacin": ["crema de calabacin", "pure de calabacin"],
  "gachas-avena": ["porridge", "gachas", "avena cocida"],
  "huevos-revueltos": ["huevos revueltos", "revuelto de huevo", "scrambled eggs"],
  "tortilla-francesa-queso": ["tortilla francesa", "omelette", "omelet"],
  "batido-platano": ["batido de platano", "smoothie de platano"],
  "bizcocho-de-yogur": ["bizcocho", "bizcocho de yogur", "bizcocho casero"],
  // Portugal
  "bacalhau-a-bras": ["bacalao a bras", "bacalhau"],
  "caldo-verde": ["caldo verde", "sopa de berza portuguesa"],
  "frango-piri-piri": ["piri piri", "frango", "pollo picante portugues"],
  "pasteis-de-nata": ["pasteis de nata", "pasteles de nata", "pasteis de belem"],
  // Italia
  "lasana-bolonesa": ["lasana", "lasagna", "lasagne"],
  "cacio-e-pepe": ["cacio e pepe", "pasta con queso y pimienta"],
  amatriciana: ["amatriciana", "matriciana"],
  minestrone: ["minestrone", "sopa minestrone"],
  tiramisu: ["tiramisu"],
  "ensalada-caprese": ["caprese", "ensalada de tomate y mozzarella"],
  focaccia: ["focaccia", "focacha"],
  "espaguetis-vongole": ["vongole", "espaguetis con almejas", "spaghetti alle vongole"],
  "pollo-cacciatore": ["cacciatore", "pollo a la cazadora"],
  "gnocchi-mantequilla": ["gnocchi", "noquis", "nioquis"],
  "penne-arrabbiata": ["arrabbiata", "arrabiata", "pasta picante"],
  "pasta-alla-norma": ["pasta alla norma", "pasta con berenjena"],
  "berenjenas-parmesana": ["parmigiana", "melanzane", "berenjenas gratinadas"],
  saltimbocca: ["saltimbocca"],
  "panna-cotta": ["panna cotta", "pannacotta"],
  bruschetta: ["bruschetta", "bruschettas"],
  frittata: ["frittata", "tortilla italiana"],
  "pasta-e-fagioli": ["pasta e fagioli", "pasta con alubias"],
  // Francia y Benelux
  "quiche-lorraine": ["quiche", "quiche lorraine"],
  "sopa-de-cebolla": ["sopa de cebolla", "soupe a l oignon"],
  "croque-monsieur": ["croque monsieur", "sandwich mixto frances"],
  "boeuf-bourguignon": ["bourguignon", "boeuf bourguignon", "ternera al vino tinto"],
  "gratin-dauphinois": ["gratin de patatas", "gratin dauphinois", "patatas gratinadas"],
  "mousse-chocolate": ["mousse de chocolate", "mousse"],
  "tarta-tatin": ["tarta tatin", "tatin", "tarta de manzana caramelizada"],
  vichyssoise: ["vichyssoise", "crema de puerros"],
  "coq-au-vin": ["coq au vin", "pollo al vino"],
  "ensalada-nicoise": ["nicoise", "ensalada nizarda"],
  "creme-brulee": ["creme brulee", "crema quemada"],
  "moules-marinieres": ["moules marinieres", "mejillones al vino blanco", "moules frites"],
  "steak-frites": ["steak frites", "entrecot con patatas", "filete con patatas"],
  // Centro y norte de Europa
  schnitzel: ["schnitzel", "escalope vienes", "wiener schnitzel"],
  kartoffelsalat: ["kartoffelsalat", "ensalada de patata alemana"],
  apfelstrudel: ["strudel", "apfelstrudel"],
  goulash: ["goulash", "gulash", "gulyas"],
  kasespatzle: ["spatzle", "kasespatzle", "spaetzle"],
  pierogi: ["pierogi", "pierogis", "empanadillas polacas"],
  "albondigas-suecas": ["albondigas suecas", "kottbullar", "albondigas ikea"],
  // Reino Unido e Irlanda
  "fish-and-chips": ["fish and chips", "pescado rebozado con patatas"],
  "cottage-pie": ["cottage pie", "shepherds pie", "pastel de carne"],
  "desayuno-ingles": ["desayuno ingles", "full english", "english breakfast"],
  "crumble-manzana": ["crumble", "crumble de manzana"],
  "irish-stew": ["irish stew", "estofado irlandes"],
  scones: ["scones", "scone"],
  // Grecia y Turquía
  spanakopita: ["spanakopita", "empanada griega"],
  gemista: ["gemista", "tomates rellenos", "pimientos rellenos de arroz"],
  fasolada: ["fasolada", "sopa de alubias griega"],
  "mercimek-corbasi": ["mercimek", "sopa de lentejas turca", "crema de lentejas"],
  "imam-bayildi": ["imam bayildi", "berenjenas rellenas"],
  lahmacun: ["lahmacun", "pizza turca"],
  "pollo-griego-limon": ["pollo griego", "kotopoulo lemonato"],
  tzatziki: ["tzatziki", "salsa de yogur y pepino", "cacik"],
  baklava: ["baklava", "baclava"],
  // India
  "tikka-masala": ["tikka masala", "chicken tikka", "pollo tikka"],
  "aloo-gobi": ["aloo gobi", "patata y coliflor al curry"],
  "korma-pollo": ["korma", "curry suave"],
  "biryani-pollo": ["biryani", "biriyani"],
  "lassi-mango": ["lassi", "mango lassi"],
  "pollo-tandoori": ["tandoori", "pollo tandori"],
  "chana-saag": ["chana saag", "chana masala", "curry de garbanzos"],
  "dal-makhani": ["dal makhani", "daal", "curry de frijoles"],
  raita: ["raita", "salsa de yogur india"],
  naan: ["naan", "pan indio"],
  samosas: ["samosa", "samosas"],
  // China
  "chow-mein": ["chow mein", "fideos chinos salteados", "tallarines chinos"],
  "mapo-tofu": ["mapo tofu", "tofu picante"],
  "tomate-con-huevo": ["tomate con huevo", "huevo con tomate chino"],
  "pollo-almendras": ["pollo con almendras", "pollo almendrado"],
  "pollo-al-limon-chino": ["pollo al limon chino", "pollo al limon"],
  "ternera-brocoli": ["ternera con brocoli", "beef and broccoli"],
  "rollitos-primavera": ["rollitos de primavera", "rollito de primavera", "spring rolls"],
  "sopa-wonton": ["wonton", "wantan", "sopa wantan"],
  // Japón
  okonomiyaki: ["okonomiyaki"],
  yakisoba: ["yakisoba", "fideos japoneses salteados"],
  "katsu-curry": ["katsu", "curry japones", "tonkatsu"],
  tamagoyaki: ["tamagoyaki", "tortilla japonesa"],
  gyoza: ["gyoza", "gyozas", "empanadillas japonesas"],
  "sopa-miso": ["sopa de miso", "miso soup", "misoshiru"],
  "salmon-teriyaki": ["teriyaki", "salmon teriyaki"],
  yakitori: ["yakitori", "brochetas japonesas"],
  "onigiri-atun": ["onigiri", "bolas de arroz"],
  // Corea
  japchae: ["japchae", "fideos de boniato"],
  "kimchi-bokkeumbap": ["arroz frito con kimchi", "kimchi bokkeumbap"],
  dakgalbi: ["dakgalbi", "pollo coreano picante"],
  "kimchi-jjigae": ["kimchi jjigae", "guiso de kimchi", "sopa de kimchi"],
  pajeon: ["pajeon", "tortita coreana", "pancake coreano"],
  // Sudeste asiático
  "curry-verde-pollo": ["curry verde", "green curry", "curry tailandes"],
  "tom-yum-gambas": ["tom yum", "sopa tailandesa picante"],
  "arroz-mango-coco": ["mango sticky rice", "arroz glutinoso con mango"],
  "pho-bo": ["pho", "sopa vietnamita"],
  "rollitos-vietnamitas": ["rollitos vietnamitas", "goi cuon", "rollitos de papel de arroz"],
  "nasi-goreng": ["nasi goreng", "arroz frito indonesio"],
  "satay-pollo": ["satay", "brochetas con salsa de cacahuete"],
  "gado-gado": ["gado gado", "ensalada indonesia"],
  "adobo-pollo": ["adobo filipino", "chicken adobo"],
  "larb-pollo": ["larb", "laab", "ensalada de pollo tailandesa"],
  "khao-pad": ["khao pad", "arroz frito tailandes"],
  "bun-cha": ["bun cha", "cerdo vietnamita"],
  laksa: ["laksa", "sopa de coco y curry"],
  // Oriente Medio y Magreb
  "shawarma-pollo": ["shawarma", "shawarma de pollo", "kebab de pollo", "doner"],
  tabule: ["tabule", "tabbouleh", "tabouleh"],
  "baba-ganoush": ["baba ganoush", "baba ganush", "pure de berenjena"],
  mujaddara: ["mujaddara", "mujadara", "arroz con lentejas"],
  fattoush: ["fattoush", "fatush", "ensalada libanesa"],
  "cuscus-verduras": ["cuscus de verduras", "couscous de verduras"],
  zaalouk: ["zaalouk", "ensalada de berenjena"],
  manakish: ["manakish", "manaeesh", "pan de zaatar"],
  muhammara: ["muhammara", "crema de pimiento"],
  "kibbeh-horno": ["kibbeh", "kibbe", "quibe"],
  "tajin-cordero-miel": ["tajin de cordero", "tagine", "tajine", "cordero con miel"],
  // México
  "pozole-rojo": ["pozole", "posole"],
  "cochinita-pibil": ["cochinita", "cochinita pibil"],
  "sopa-de-tortilla": ["sopa de tortilla", "sopa azteca"],
  "frijoles-charros": ["frijoles charros", "frijoles borrachos"],
  "burritos-ternera": ["burrito", "burritos"],
  "fajitas-pollo": ["fajitas", "fajita"],
  "arroz-mexicano": ["arroz rojo", "arroz a la mexicana"],
  "tacos-al-pastor": ["tacos al pastor", "al pastor"],
  "tinga-pollo": ["tinga", "tinga de pollo", "tostadas de tinga"],
  esquites: ["esquites", "elote", "maiz con mayonesa"],
  "chiles-rellenos": ["chiles rellenos", "chile relleno"],
  "caldo-tlalpeno": ["caldo tlalpeno", "sopa de pollo mexicana"],
  // EE. UU.
  "tortitas-americanas": ["tortitas", "pancakes", "hotcakes", "panqueques"],
  brownies: ["brownie", "brownies"],
  "chili-con-carne": ["chili", "chile con carne"],
  "costillas-bbq": ["costillas barbacoa", "costillas bbq", "ribs"],
  cheesecake: ["cheesecake", "tarta de queso al horno", "new york cheesecake"],
  "ensalada-cesar": ["ensalada cesar", "caesar salad"],
  "sopa-pollo-fideos": ["sopa de pollo", "caldo de pollo con fideos", "chicken noodle soup"],
  "pollo-frito-sureno": ["pollo frito", "fried chicken", "pollo kentucky"],
  "pulled-pork": ["pulled pork", "cerdo desmechado", "cerdo deshilachado"],
  jambalaya: ["jambalaya", "arroz cajun"],
  "cookies-chocolate": ["cookies", "galletas de chocolate", "chocolate chip cookies"],
  "banana-bread": ["banana bread", "pan de platano", "bizcocho de platano"],
  // Caribe y Centroamérica
  "ropa-vieja": ["ropa vieja", "carne desmechada cubana"],
  "moros-y-cristianos": ["moros y cristianos", "arroz congri", "congri"],
  "picadillo-cubano": ["picadillo"],
  sancocho: ["sancocho"],
  pupusas: ["pupusa", "pupusas"],
  "gallo-pinto": ["gallo pinto", "arroz con frijoles"],
  // Sudamérica
  arepas: ["arepa", "arepas"],
  ajiaco: ["ajiaco"],
  "pabellon-criollo": ["pabellon", "pabellon criollo"],
  "aji-de-gallina": ["aji de gallina"],
  "papa-huancaina": ["papa a la huancaina", "huancaina", "salsa huancaina"],
  "arroz-chaufa": ["chaufa", "arroz chaufa", "chaufa de pollo"],
  locro: ["locro"],
  provoleta: ["provoleta", "provolone a la plancha"],
  "pastel-de-choclo": ["pastel de choclo"],
  feijoada: ["feijoada"],
  brigadeiros: ["brigadeiro", "brigadeiros"],
  "bobo-gambas": ["bobo de camarao", "bobo de gambas"],
  "bandeja-paisa": ["bandeja paisa"],
  "causa-limena": ["causa", "causa limena", "causa rellena"],
  anticuchos: ["anticucho", "anticuchos"],
  "asado-chimichurri": ["chimichurri", "asado de tira", "churrasco"],
  humita: ["humita", "humitas"],
  picanha: ["picanha", "tapilla", "churrasco brasileno"],
  "arepa-reina-pepiada": ["reina pepiada", "arepa de pollo y aguacate"],
  // África
  "jollof-rice": ["jollof", "arroz jollof"],
  "misir-wot": ["misir wot", "lentejas etiopes"],
  "pollo-yassa": ["yassa", "pollo yassa"],
  bobotie: ["bobotie"],
  mafe: ["mafe", "guiso de cacahuete", "maafe"],
  suya: ["suya", "brochetas nigerianas"],
  "doro-wat": ["doro wat", "doro wot", "pollo etiope"],
  koshari: ["koshari", "kushari", "koshary"],
  "bunny-chow": ["bunny chow", "curry en pan"],
  "tarta-de-santiago": ["tarta de santiago", "tarta de almendra"],
  "churros-con-chocolate": ["churros", "porras", "chocolate con churros"],
  "tarta-de-la-abuela": ["tarta de la abuela", "tarta de galletas"],
  "peras-al-vino": ["peras al vino"],
  "brazo-gitano": ["brazo de gitano", "brazo gitano"],
  "bunuelos-de-viento": ["bunuelos", "bunuelos de viento"],
  "mousse-de-limon": ["mousse de limon"],
  "coulant-chocolate": ["coulant", "volcan de chocolate", "fondant de chocolate"],
  "clafoutis-peras": ["clafoutis"],
  "tarta-zanahoria": ["carrot cake", "tarta de zanahoria"],
  "banoffee": ["banoffee", "banoffee pie"],
  "shortbread": ["shortbread", "galletas de mantequilla"],
  "pudin-de-pan": ["pudin de pan", "bread pudding"],
  "apple-pie": ["apple pie", "tarta de manzana"],
  "key-lime-pie": ["key lime pie", "tarta de lima"],
  "pumpkin-pie": ["pumpkin pie", "tarta de calabaza"],
  "mug-cake": ["mug cake", "bizcocho en taza", "bizcocho de microondas"],
  "tres-leches": ["tres leches", "pastel tres leches"],
  "alfajores-maicena": ["alfajores", "alfajor"],
  "quesillo": ["quesillo"],
  "kheer": ["kheer"],
  "dorayaki": ["dorayaki"],
  "pavlova": ["pavlova"],
  "helado-platano": ["nice cream", "helado de platano"],
  "tocino-de-cielo": ["tocino de cielo"],
  "leche-merengada": ["leche merengada"],
  "trufas-chocolate": ["trufas"],
  "wok-pad-krapow": ["pad krapow", "pad kra pao", "pollo con albahaca"],
  "wok-cerdo-agridulce": ["cerdo agridulce", "sweet and sour"],
  "wok-pollo-teriyaki": ["pollo teriyaki"],
};

/**
 * Etiquetas solo para el buscador (no para pedir un plato concreto): técnica,
 * utensilio o región. Aquí sí valen términos que agrupan muchas recetas.
 */
export const SEARCH_TAGS: Record<string, string[]> = {};
const tag = (t: string[], ids: string[]) => ids.forEach((id) => (SEARCH_TAGS[id] = [...(SEARCH_TAGS[id] ?? []), ...t]));

tag(["wok", "salteado", "stir fry"], [
  "chow-mein", "yakisoba", "nasi-goreng", "arroz-chaufa", "japchae", "kimchi-bokkeumbap", "dakgalbi", "khao-pad",
  "ternera-brocoli", "pollo-almendras", "tomate-con-huevo", "mapo-tofu", "pad-thai", "lomo-saltado", "arroz-tres-delicias",
  "pollo-kung-pao", "wok-verduras-tofu", "wok-ternera-pimientos", "wok-gambas-ajo", "wok-pollo-anacardos", "wok-cerdo-agridulce",
  "wok-fideos-verduras", "wok-pollo-teriyaki", "wok-pad-krapow",
]);
tag(["asturias", "asturiano", "asturiana", "cocina asturiana"], [
  "fabada-asturiana", "cachopo", "arroz-con-leche", "frixuelos", "merluza-a-la-sidra", "carne-gobernada", "chorizo-a-la-sidra",
  "casadielles", "fabes-con-almejas", "arroz-con-pitu", "escalopines-cabrales",
]);

/** Postres y dulces: alimentan el filtro rápido «Postres» y la búsqueda de «postre». */
export const DESSERTS = [
  "flan-de-huevo", "arroz-con-leche", "crema-catalana", "torrijas", "leche-frita", "frixuelos", "casadielles", "pasteis-de-nata",
  "tiramisu", "panna-cotta", "creme-brulee", "mousse-chocolate", "tarta-tatin", "apfelstrudel", "crumble-manzana", "scones", "baklava",
  "lassi-mango", "arroz-mango-coco", "tortitas-americanas", "brownies", "cheesecake", "brigadeiros", "tarta-de-queso-vasca", "natillas",
  "bizcocho-de-yogur", "cookies-chocolate", "banana-bread", "crepes",
  "tarta-de-santiago", "churros-con-chocolate", "magdalenas", "tarta-de-la-abuela", "peras-al-vino", "tocino-de-cielo", "brazo-gitano",
  "bunuelos-de-viento", "mousse-de-limon", "fresas-con-nata", "rosquillas", "macedonia", "leche-merengada", "manzanas-asadas",
  "coulant-chocolate", "clafoutis-peras", "trufas-chocolate", "tarta-zanahoria", "banoffee", "shortbread", "pudin-de-pan", "tarta-queso-fria",
  "apple-pie", "key-lime-pie", "pumpkin-pie", "mug-cake", "tres-leches", "alfajores-maicena", "quesillo", "kheer", "dorayaki", "pavlova",
  "yogur-miel-nueces", "helado-platano",
];
tag(["postre", "postres", "dulce", "merienda"], DESSERTS);
