import type { Aisle, Ingredient, Price, UnitId, UnitKind } from "@comocomo/schemas";

type Row = [id: string, name: string, aisle: Aisle, kind: UnitKind, allergens: string[], tags: string[], price: [unit: UnitId, min: number, max: number]];

const MILK = ["milk", "lactose"];

/**
 * Ingredientes + precio de referencia (EUR, España, supermercado, 2026).
 * Los precios son ESTIMACIONES orientativas, no datos de tienda: confidence = "estimated".
 */
const rows: Row[] = [
  ["pollo", "Pollo (muslos o pechuga)", "butcher", "mass", [], ["meat", "poultry"], ["kg", 5, 8]],
  ["chorizo", "Chorizo", "butcher", "mass", [], ["meat", "pork"], ["kg", 8, 14]],
  ["morcilla", "Morcilla asturiana", "butcher", "mass", [], ["meat", "pork"], ["kg", 7, 11]],
  ["panceta", "Panceta o tocino", "butcher", "mass", [], ["meat", "pork"], ["kg", 6, 11]],
  ["merluza", "Merluza (lomos)", "fish", "mass", ["fish"], ["fish", "seafood"], ["kg", 9, 14]],
  ["gambas", "Gambas", "fish", "mass", ["shellfish"], ["seafood"], ["kg", 12, 22]],
  ["huevo", "Huevos", "dairy", "count", ["egg"], [], ["unit", 0.2, 0.35]],
  ["leche", "Leche", "dairy", "volume", MILK, [], ["l", 0.9, 1.3]],
  ["queso", "Queso (curado, rallado o para fundir)", "dairy", "mass", MILK, [], ["kg", 8, 14]],
  ["mantequilla", "Mantequilla", "dairy", "mass", MILK, [], ["kg", 8, 12]],
  ["yogur", "Yogur natural", "dairy", "count", MILK, [], ["unit", 0.25, 0.5]],
  ["patata", "Patatas", "produce", "mass", [], [], ["kg", 1, 1.8]],
  ["cebolla", "Cebolla", "produce", "count", [], ["allium"], ["unit", 0.2, 0.4]],
  ["ajo", "Dientes de ajo", "produce", "count", [], ["allium"], ["unit", 0.05, 0.1]],
  ["tomate", "Tomate", "produce", "mass", [], [], ["kg", 2, 3.5]],
  ["pimiento", "Pimiento", "produce", "count", [], [], ["unit", 0.5, 0.9]],
  ["zanahoria", "Zanahoria", "produce", "mass", [], [], ["kg", 1, 1.6]],
  ["calabacin", "Calabacín", "produce", "mass", [], [], ["kg", 1.5, 2.5]],
  ["espinacas", "Espinacas", "produce", "mass", [], [], ["kg", 5, 8]],
  ["aguacate", "Aguacate", "produce", "count", [], [], ["unit", 0.8, 1.5]],
  ["limon", "Limón", "produce", "count", [], [], ["unit", 0.25, 0.5]],
  ["lima", "Lima", "produce", "count", [], [], ["unit", 0.2, 0.4]],
  ["chile", "Chile o guindilla", "produce", "count", [], [], ["unit", 0.1, 0.25]],
  ["jengibre", "Jengibre fresco", "produce", "mass", [], [], ["kg", 6, 10]],
  ["cilantro", "Cilantro fresco", "produce", "mass", [], [], ["kg", 15, 30]],
  ["perejil", "Perejil fresco", "produce", "mass", [], [], ["kg", 15, 25]],
  ["albahaca", "Albahaca fresca", "produce", "mass", [], [], ["kg", 30, 60]],
  ["arroz", "Arroz", "pantry", "mass", [], [], ["kg", 1.2, 2]],
  ["pasta", "Pasta seca", "pantry", "mass", ["gluten"], [], ["kg", 1.2, 2.2]],
  ["harina", "Harina de trigo", "pantry", "mass", ["gluten"], [], ["kg", 0.9, 1.5]],
  ["pan-rallado", "Pan rallado", "pantry", "mass", ["gluten"], [], ["kg", 1.5, 2.5]],
  ["garbanzos", "Garbanzos secos", "pantry", "mass", [], [], ["kg", 2, 3.5]],
  ["lentejas", "Lentejas secas", "pantry", "mass", [], [], ["kg", 2, 3.5]],
  ["fabes", "Fabes (alubias blancas secas)", "pantry", "mass", [], [], ["kg", 7, 12]],
  ["tomate-triturado", "Tomate triturado", "pantry", "mass", [], [], ["kg", 1.5, 2.5]],
  ["leche-coco", "Leche de coco", "pantry", "volume", [], [], ["l", 2.5, 4.5]],
  ["caldo", "Caldo de verduras", "pantry", "volume", [], [], ["l", 0.6, 1.5]],
  ["aceite", "Aceite de oliva", "pantry", "volume", [], [], ["l", 5, 9]],
  ["vinagre", "Vinagre", "pantry", "volume", ["sulfites"], [], ["l", 1, 2]],
  ["vino-blanco", "Vino blanco", "pantry", "volume", ["sulfites"], [], ["l", 2, 4]],
  ["soja", "Salsa de soja", "pantry", "volume", ["soy", "gluten"], [], ["l", 4, 8]],
  ["azucar", "Azúcar", "pantry", "mass", [], [], ["kg", 1, 1.5]],
  ["sal", "Sal", "pantry", "mass", [], [], ["kg", 0.5, 1]],
  ["pimenton", "Pimentón", "pantry", "mass", [], [], ["kg", 16, 28]],
  ["comino", "Comino molido", "pantry", "mass", [], [], ["kg", 25, 40]],
  ["curry", "Curry en polvo", "pantry", "mass", [], [], ["kg", 25, 40]],
  ["pimienta", "Pimienta negra", "pantry", "mass", [], [], ["kg", 30, 50]],
  ["pan", "Pan (del día anterior)", "bakery", "mass", ["gluten"], [], ["kg", 2.5, 4]],
  ["tortilla-maiz", "Tortillas de maíz", "bakery", "count", [], [], ["unit", 0.08, 0.15]],
  // — lote 2 —
  ["oregano", "Orégano seco", "pantry", "mass", [], [], ["kg", 40, 70]],
  ["calamares", "Calamares", "fish", "mass", ["mollusc"], ["seafood"], ["kg", 8, 14]],
  ["champinones", "Champiñones", "produce", "mass", [], [], ["kg", 4, 7]],
  ["pepino", "Pepino", "produce", "mass", [], [], ["kg", 1.5, 2.5]],
  ["feta", "Queso feta", "dairy", "mass", MILK, [], ["kg", 8, 14]],
  ["aceitunas", "Aceitunas", "pantry", "mass", [], [], ["kg", 4, 8]],
  ["pan-pita", "Pan de pita", "bakery", "count", ["gluten"], [], ["unit", 0.3, 0.6]],
  ["cuscus", "Cuscús", "pantry", "mass", ["gluten"], [], ["kg", 2, 3.5]],
  ["garbanzos-cocidos", "Garbanzos cocidos (bote)", "pantry", "mass", [], [], ["kg", 1.5, 2.5]],
  ["sesamo", "Semillas de sésamo", "pantry", "mass", ["sesame"], [], ["kg", 8, 14]],
  ["cacahuetes", "Cacahuetes", "pantry", "mass", ["peanut", "nuts"], [], ["kg", 5, 9]],
  // — lote 3 —
  ["ternera-picada", "Carne picada de ternera", "butcher", "mass", [], ["meat"], ["kg", 7, 10]],
  ["ternera", "Ternera en filetes", "butcher", "mass", [], ["meat"], ["kg", 12, 17]],
  ["cerdo", "Lomo o magro de cerdo", "butcher", "mass", [], ["meat", "pork"], ["kg", 6, 9]],
  ["jamon", "Jamón serrano en lonchas", "butcher", "mass", [], ["meat", "pork"], ["kg", 18, 30]],
  ["salmon", "Salmón (lomos)", "fish", "mass", ["fish"], ["fish", "seafood"], ["kg", 14, 20]],
  ["nata", "Nata para cocinar", "dairy", "volume", MILK, [], ["l", 3, 5]],
  ["mozzarella", "Mozzarella", "dairy", "mass", MILK, [], ["kg", 7, 11]],
  ["tofu", "Tofu firme", "dairy", "mass", ["soy"], [], ["kg", 6, 9]],
  ["fideos-arroz", "Fideos de arroz", "pantry", "mass", [], [], ["kg", 6, 9]],
  ["fideos-ramen", "Fideos de trigo (ramen)", "pantry", "mass", ["gluten"], [], ["kg", 6, 10]],
  ["levadura", "Levadura seca de panadería", "pantry", "mass", [], [], ["kg", 25, 45]],
  ["obleas-empanadilla", "Obleas para empanadillas", "dairy", "count", ["gluten"], [], ["unit", 0.12, 0.2]],
  ["pan-hamburguesa", "Pan de hamburguesa", "bakery", "count", ["gluten"], [], ["unit", 0.3, 0.5]],
  ["berenjena", "Berenjena", "produce", "mass", [], [], ["kg", 1.8, 2.8]],
  ["lechuga", "Lechuga", "produce", "count", [], [], ["unit", 0.6, 1]],
  ["cebolleta", "Cebolleta", "produce", "count", [], ["allium"], ["unit", 0.3, 0.5]],
  ["judias-verdes", "Judías verdes", "produce", "mass", [], [], ["kg", 3, 5]],
  ["frijoles-negros", "Frijoles negros cocidos", "pantry", "mass", [], [], ["kg", 3, 5]],
  ["tahini", "Tahini (crema de sésamo)", "pantry", "mass", ["sesame"], [], ["kg", 10, 16]],
  ["canela", "Canela en rama", "pantry", "mass", [], [], ["kg", 40, 70]],
  ["pinones", "Piñones", "pantry", "mass", ["nuts"], [], ["kg", 50, 80]],
  // — lote 4 —
  ["cordero", "Cordero (paletilla o pierna)", "butcher", "mass", [], ["meat"], ["kg", 12, 18]],
  ["costillas-cerdo", "Costillas de cerdo", "butcher", "mass", [], ["meat", "pork"], ["kg", 6, 9]],
  ["salchichas", "Salchichas frescas", "butcher", "mass", [], ["meat", "pork"], ["kg", 6, 9]],
  ["bacalao", "Bacalao desalado", "fish", "mass", ["fish"], ["fish", "seafood"], ["kg", 14, 20]],
  ["atun-lata", "Atún en lata", "pantry", "mass", ["fish"], ["fish", "seafood"], ["kg", 12, 18]],
  ["mejillones", "Mejillones", "fish", "mass", ["mollusc"], ["seafood"], ["kg", 3, 5]],
  ["almejas", "Almejas", "fish", "mass", ["mollusc"], ["seafood"], ["kg", 12, 20]],
  ["pulpo", "Pulpo cocido", "fish", "mass", ["mollusc"], ["seafood"], ["kg", 25, 35]],
  ["parmesano", "Parmesano", "dairy", "mass", MILK, [], ["kg", 18, 28]],
  ["mascarpone", "Mascarpone", "dairy", "mass", MILK, [], ["kg", 9, 14]],
  ["boniato", "Boniato", "produce", "mass", [], [], ["kg", 1.8, 2.8]],
  ["calabaza", "Calabaza", "produce", "mass", [], [], ["kg", 1.2, 2]],
  ["coliflor", "Coliflor", "produce", "count", [], [], ["unit", 1.5, 2.5]],
  ["brocoli", "Brócoli", "produce", "count", [], [], ["unit", 1.2, 2]],
  ["puerro", "Puerro", "produce", "count", [], ["allium"], ["unit", 0.6, 1]],
  ["apio", "Apio", "produce", "mass", [], [], ["kg", 2, 3.5]],
  ["guisantes", "Guisantes congelados", "frozen", "mass", [], [], ["kg", 2.5, 4]],
  ["maiz", "Maíz dulce en lata", "pantry", "mass", [], [], ["kg", 3, 5]],
  ["alubias-blancas", "Alubias blancas cocidas", "pantry", "mass", [], [], ["kg", 2, 3.5]],
  ["harina-maiz", "Harina de maíz precocida", "pantry", "mass", [], [], ["kg", 2.5, 4]],
  ["masa-hojaldre", "Masa de hojaldre o quebrada", "dairy", "mass", ["gluten", "milk", "lactose"], [], ["kg", 6, 9]],
  ["laminas-lasana", "Láminas de lasaña", "pantry", "mass", ["gluten", "egg"], [], ["kg", 4, 7]],
  ["papel-arroz", "Obleas de papel de arroz", "pantry", "count", [], [], ["unit", 0.08, 0.15]],
  ["chocolate", "Chocolate negro", "pantry", "mass", ["milk"], [], ["kg", 10, 16]],
  ["cacao", "Cacao en polvo", "pantry", "mass", [], [], ["kg", 10, 16]],
  ["leche-condensada", "Leche condensada", "pantry", "mass", MILK, [], ["kg", 4, 6]],
  ["cafe", "Café molido o soluble", "pantry", "mass", [], [], ["kg", 12, 20]],
  ["bizcochos", "Bizcochos de soletilla", "bakery", "mass", ["gluten", "egg"], [], ["kg", 7, 11]],
  ["nueces", "Nueces", "pantry", "mass", ["nuts"], [], ["kg", 10, 16]],
  ["almendras", "Almendras", "pantry", "mass", ["nuts"], [], ["kg", 10, 16]],
  ["manzana", "Manzana", "produce", "count", [], [], ["unit", 0.3, 0.5]],
  ["platano", "Plátano", "produce", "count", [], [], ["unit", 0.2, 0.35]],
  ["naranja", "Naranja", "produce", "count", [], [], ["unit", 0.25, 0.45]],
  ["mango", "Mango", "produce", "count", [], [], ["unit", 1.2, 2]],
  ["sidra", "Sidra natural", "pantry", "volume", ["sulfites"], [], ["l", 2.5, 4]],
  ["mostaza", "Mostaza", "pantry", "mass", ["mustard"], [], ["kg", 6, 10]],
  ["miel", "Miel", "pantry", "mass", [], [], ["kg", 8, 14]],
  ["menta", "Menta fresca", "produce", "mass", [], [], ["kg", 20, 40]],
  ["kimchi", "Kimchi", "pantry", "mass", ["shellfish"], ["seafood"], ["kg", 12, 18]],
  ["pasta-curry-verde", "Pasta de curry verde (suele llevar pasta de gamba)", "pantry", "mass", ["shellfish"], ["seafood"], ["kg", 12, 20]],
  ["bulgur", "Bulgur", "pantry", "mass", ["gluten"], [], ["kg", 3, 5]],
  ["arroz-basmati", "Arroz basmati", "pantry", "mass", [], [], ["kg", 3, 5]],
  ["repollo", "Repollo (col)", "produce", "count", [], [], ["unit", 1, 1.8]],
  ["tortilla-trigo", "Tortillas de trigo", "bakery", "count", ["gluten"], [], ["unit", 0.15, 0.3]],
  ["levadura-quimica", "Levadura química (polvo de hornear)", "pantry", "mass", [], [], ["kg", 15, 30]],
  ["queso-crema", "Queso crema", "dairy", "mass", MILK, [], ["kg", 7, 11]],
  ["galletas", "Galletas tipo María", "pantry", "mass", ["gluten"], [], ["kg", 2.5, 4]],
  ["queso-azul", "Queso azul (Cabrales o similar)", "dairy", "mass", ["milk", "lactose"], [], ["kg", 15, 25]],
  ["avena", "Copos de avena", "pantry", "mass", ["gluten"], [], ["kg", 1.5, 3]],
  ["gelatina", "Gelatina en hojas", "pantry", "count", [], ["meat"], ["unit", 0.1, 0.2]],
  ["miso", "Pasta de miso", "pantry", "mass", ["soy"], [], ["kg", 12, 20]],
  ["nori", "Alga nori", "pantry", "count", [], [], ["unit", 0.2, 0.4]],
  ["vino-tinto", "Vino tinto", "pantry", "volume", ["sulfites"], [], ["l", 3, 6]],
  ["pera", "Pera", "produce", "count", [], [], ["unit", 0.3, 0.5]],
  ["fresas", "Fresas", "produce", "mass", [], [], ["kg", 3, 6]],
  ["dulce-de-leche", "Dulce de leche", "pantry", "mass", MILK, [], ["kg", 7, 11]],
  ["coco-rallado", "Coco rallado", "pantry", "mass", [], [], ["kg", 8, 14]],
  ["pasta-curry-rojo", "Pasta de curry rojo (suele llevar pasta de gamba)", "pantry", "mass", ["shellfish"], ["seafood"], ["kg", 12, 20]],
];

type Pack = [qty: number, unit: UnitId, label: string];
/**
 * Envases habituales en supermercados españoles. Lo que no aparece se compra a granel
 * (fruta y verdura suelta, pescado y carne al corte). Tamaños orientativos.
 */
const PACKS: Record<string, Pack> = {
  pollo: [500, "g", "bandeja"], chorizo: [225, "g", "sarta"], morcilla: [250, "g", "paquete"], panceta: [200, "g", "paquete"],
  gambas: [400, "g", "bolsa"], huevo: [6, "unit", "media docena"], leche: [1, "l", "brik"], queso: [200, "g", "paquete"],
  mantequilla: [250, "g", "pastilla"], yogur: [4, "unit", "pack"], ajo: [10, "unit", "cabeza"], espinacas: [300, "g", "bolsa"],
  cilantro: [30, "g", "manojo"], perejil: [40, "g", "manojo"], albahaca: [20, "g", "tarrina"], champinones: [250, "g", "bandeja"],
  arroz: [1, "kg", "paquete"], pasta: [500, "g", "paquete"], harina: [1, "kg", "paquete"], "pan-rallado": [250, "g", "paquete"],
  garbanzos: [500, "g", "paquete"], lentejas: [500, "g", "paquete"], fabes: [500, "g", "paquete"], "tomate-triturado": [400, "g", "bote"],
  "leche-coco": [400, "ml", "lata"], caldo: [1, "l", "brik"], aceite: [1, "l", "botella"], vinagre: [500, "ml", "botella"],
  "vino-blanco": [750, "ml", "botella"], soja: [150, "ml", "botella"], azucar: [1, "kg", "paquete"], sal: [1, "kg", "paquete"],
  pimenton: [75, "g", "bote"], comino: [40, "g", "bote"], curry: [40, "g", "bote"], pimienta: [50, "g", "bote"], oregano: [15, "g", "bote"],
  pan: [250, "g", "barra"], "tortilla-maiz": [10, "unit", "paquete"], feta: [200, "g", "paquete"], aceitunas: [200, "g", "bote"],
  "pan-pita": [6, "unit", "paquete"], cuscus: [500, "g", "paquete"], "garbanzos-cocidos": [400, "g", "bote"], sesamo: [100, "g", "bolsa"],
  cacahuetes: [150, "g", "bolsa"], "pasta-curry-rojo": [110, "g", "tarro"],
  "ternera-picada": [500, "g", "bandeja"], ternera: [400, "g", "bandeja"], cerdo: [500, "g", "bandeja"], jamon: [100, "g", "paquete"],
  nata: [200, "ml", "brik"], mozzarella: [125, "g", "bola"], tofu: [400, "g", "bloque"], "fideos-arroz": [250, "g", "paquete"],
  "fideos-ramen": [250, "g", "paquete"], levadura: [50, "g", "paquete"], "obleas-empanadilla": [16, "unit", "paquete"],
  "pan-hamburguesa": [4, "unit", "paquete"], cebolleta: [3, "unit", "manojo"], "frijoles-negros": [400, "g", "bote"],
  tahini: [300, "g", "tarro"], canela: [30, "g", "bote"], pinones: [50, "g", "bolsa"],
  cordero: [500, "g", "bandeja"], "costillas-cerdo": [800, "g", "bandeja"], salchichas: [400, "g", "bandeja"], bacalao: [400, "g", "bandeja"],
  "atun-lata": [160, "g", "pack de 3 latas"], mejillones: [1, "kg", "malla"], almejas: [250, "g", "bandeja"], pulpo: [250, "g", "bandeja"],
  parmesano: [150, "g", "cuña"], mascarpone: [250, "g", "tarrina"], guisantes: [400, "g", "bolsa"], maiz: [280, "g", "lata"],
  "alubias-blancas": [400, "g", "bote"], "harina-maiz": [1, "kg", "paquete"], "masa-hojaldre": [275, "g", "lámina"],
  "laminas-lasana": [250, "g", "paquete"], "papel-arroz": [20, "unit", "paquete"], chocolate: [100, "g", "tableta"], cacao: [250, "g", "bote"],
  "leche-condensada": [370, "g", "bote"], cafe: [250, "g", "paquete"], bizcochos: [200, "g", "paquete"], nueces: [200, "g", "bolsa"],
  almendras: [200, "g", "bolsa"], sidra: [700, "ml", "botella"], mostaza: [200, "g", "tarro"], miel: [500, "g", "tarro"], menta: [20, "g", "tarrina"],
  kimchi: [300, "g", "tarro"], "pasta-curry-verde": [110, "g", "tarro"], bulgur: [500, "g", "paquete"], "arroz-basmati": [500, "g", "paquete"],
  "vino-tinto": [750, "ml", "botella"], "tortilla-trigo": [8, "unit", "paquete"], "levadura-quimica": [50, "g", "paquete"],
  "queso-crema": [300, "g", "tarrina"], galletas: [200, "g", "paquete"],
  "queso-azul": [150, "g", "cuña"], avena: [500, "g", "paquete"], gelatina: [12, "unit", "sobre"], miso: [300, "g", "tarrina"], nori: [10, "unit", "paquete"],
  fresas: [500, "g", "tarrina"], "dulce-de-leche": [450, "g", "bote"], "coco-rallado": [125, "g", "bolsa"],
};

const ALIASES: Record<string, string[]> = {
  pollo: ["pechuga", "pechugas", "muslo", "muslos", "contramuslo", "contramuslos"],
  huevo: ["huevos"],
  patata: ["patatas", "papa", "papas"],
  tomate: ["tomates"],
  pimiento: ["pimientos"],
  ajo: ["ajos"],
  zanahoria: ["zanahorias"],
  pasta: ["espagueti", "espaguetis", "spaghetti", "macarrones", "fideos", "tallarines"],
  queso: ["quesos", "parmesano", "mozzarella", "mozarela", "manchego", "cheddar"],
  chorizo: ["chorizos"],
  gambas: ["gamba", "langostinos", "langostino"],
  merluza: ["pescado blanco"],
  lentejas: ["lenteja"],
  garbanzos: ["garbanzo"],
  fabes: ["fabas", "alubias", "judias blancas"],
  aceite: ["aceite de oliva"],
  "tomate-triturado": ["tomate frito", "salsa de tomate"],
  pan: ["barra de pan"],
  limon: ["limones"],
  cebolla: ["cebollas"],
  aguacate: ["aguacates"],
  "tortilla-maiz": ["tortillas", "tortillas de maiz", "tortillas mexicanas"],
  "leche-coco": ["leche de coco"],
  soja: ["salsa de soja"],
  panceta: ["bacon", "beicon", "tocino"],
  calabacin: ["calabacines"],
  espinacas: ["espinaca"],
  oregano: ["oregano"],
  calamares: ["calamar", "chipirones", "chipiron"],
  champinones: ["champinon", "setas"],
  pepino: ["pepinos"],
  feta: ["queso feta"],
  aceitunas: ["aceituna", "olivas"],
  "pan-pita": ["pita", "pan arabe"],
  cuscus: ["couscous", "cous cous"],
  "garbanzos-cocidos": ["garbanzos cocidos", "bote de garbanzos"],
  sesamo: ["ajonjoli"],
  cacahuetes: ["cacahuete", "mani"],
  "ternera-picada": ["carne picada", "picada", "carne molida"],
  ternera: ["filete", "filetes", "vaca", "carne de ternera"],
  cerdo: ["lomo", "magro", "carne de cerdo", "puerco"],
  jamon: ["jamon serrano"],
  salmon: ["salmon"],
  mozzarella: ["mozarela"],
  "fideos-arroz": ["fideos de arroz", "noodles de arroz"],
  "fideos-ramen": ["ramen", "noodles", "fideos chinos"],
  "obleas-empanadilla": ["obleas", "masa de empanadillas"],
  berenjena: ["berenjenas"],
  cebolleta: ["cebolletas", "cebolla tierna"],
  "judias-verdes": ["judias verdes", "vainas"],
  "frijoles-negros": ["frijoles", "alubias negras"],
  repollo: ["col", "berza", "repollos"],
  "queso-azul": ["cabrales", "queso de cabrales", "roquefort", "gorgonzola"], avena: ["copos de avena", "porridge"], nori: ["algas"],
  "tortilla-trigo": ["tortillas de trigo", "wraps"], "queso-crema": ["philadelphia", "queso de untar"], galletas: ["galleta"],
  cordero: ["cabrito"], "costillas-cerdo": ["costillas", "costilla"], salchichas: ["salchicha"], bacalao: ["bacalao"],
  "atun-lata": ["atun", "bonito"], mejillones: ["mejillon"], almejas: ["almeja"], pulpo: ["pulpo"], parmesano: ["parmigiano"],
  boniato: ["batata", "camote"], calabaza: ["zapallo"], brocoli: ["brecol"], guisantes: ["arvejas", "chicharos"], maiz: ["choclo", "elote"],
  "alubias-blancas": ["alubias", "judias blancas cocidas"], "harina-maiz": ["harina pan", "masa de arepa"], "masa-hojaldre": ["hojaldre", "masa quebrada"],
  "laminas-lasana": ["lasana", "placas de lasana"], chocolate: ["chocolate negro"], manzana: ["manzanas"], platano: ["platanos", "banana", "bananas"],
  naranja: ["naranjas"], "arroz-basmati": ["basmati"],
};

export const ingredients: Ingredient[] = rows.map(([id, name, aisle, unitKind, allergens, tags]) => ({
  id, name, aisle, unitKind, allergens, tags, aliases: ALIASES[id] ?? [],
  ...(PACKS[id] ? { pack: { qty: PACKS[id]![0], unit: PACKS[id]![1], label: PACKS[id]![2] } } : {}),
}));

export const prices: Price[] = rows.map(([ingredientId, , , , , , [perUnit, min, max]]) => ({
  ingredientId, perUnit, currency: "EUR", min, max, confidence: "estimated",
}));

export const EQUIPMENT = ["sarten", "olla", "horno", "batidora", "airfryer", "microondas"] as const;
