import type { Recipe } from "@comocomo/schemas";
import { I, r, S } from "./helpers";

/** Lote 4B: Italia, Francia, Alemania, Reino Unido, Grecia y Turquía. Recetas escritas para COMOCOMO. */
export const recipesEuropa: Recipe[] = [
  // ——— Italia ———
  r({
    id: "lasana-bolonesa", title: "Lasaña boloñesa", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia (Emilia-Romaña)", baseServings: 6, prepMin: 30, cookMin: 90, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("laminas-lasana", 250, "g"), I("ternera-picada", 500, "g"), I("cebolla", 1, "unit"), I("zanahoria", 100, "g"), I("tomate-triturado", 400, "g"), I("vino-tinto", 100, "ml"), I("leche", 700, "ml"), I("mantequilla", 60, "g"), I("harina", 60, "g"), I("parmesano", 80, "g"), I("aceite", 30, "ml"), I("sal", 8, "g")],
    steps: [
      S("Pocha la cebolla y la zanahoria picadas en el aceite 10 minutos. Añade la carne y dórala 8 minutos. Agrega el vino, el tomate y 4 g de sal y cocina a fuego suave 30 minutos.", 48),
      S("Para la bechamel, funde la mantequilla, tuesta la harina 2 minutos y añade la leche poco a poco, removiendo 8 minutos hasta que espese. Sala.", 10),
      S("Precalienta el horno a 190 °C. Si las láminas no son precocidas, hiérvelas 2 minutos menos de lo que indica el paquete.", 8, 190),
      S("En una fuente, alterna capas: bechamel, láminas, ragú, bechamel y parmesano. Termina con bechamel y parmesano."),
      S("Hornea 30 minutos hasta que esté dorada y burbujee. Deja reposar 10 minutos antes de cortar.", 30, 190),
    ],
  }),
  r({
    id: "cacio-e-pepe", title: "Cacio e pepe", cuisine: "italiana", authenticity: "adapted",
    origin: "Italia (Roma)", note: "Se hace con pecorino romano; con parmesano queda algo más suave. El truco es emulsionar el queso con el agua de la pasta, sin fuego directo.",
    baseServings: 2, prepMin: 5, cookMin: 15, difficulty: "medium", equipment: ["olla", "sarten"],
    ingredients: [I("pasta", 200, "g"), I("parmesano", 80, "g"), I("pimienta", 4, "g"), I("sal", 8, "g")],
    steps: [
      S("Hierve la pasta en poca agua (1,5 litros) con poca sal: el agua debe quedar muy almidonada.", 2),
      S("Tuesta la pimienta recién molida en una sartén seca 1 minuto. Añade un cucharón de agua de la pasta.", 1),
      S("Mezcla el queso rallado muy fino con unas cucharadas de agua de la pasta templada hasta formar una crema.", 1),
      S("Pasa la pasta al dente a la sartén con la pimienta, apaga el fuego, añade la crema de queso y remueve enérgicamente 1 minuto, añadiendo agua si hace falta, hasta que quede sedosa.", 1),
    ],
  }),
  r({
    id: "amatriciana", title: "Pasta all'amatriciana", cuisine: "italiana", authenticity: "adapted",
    origin: "Italia (Amatrice, Lacio)", note: "La original lleva guanciale y pecorino; aquí, panceta y parmesano.",
    baseServings: 2, prepMin: 10, cookMin: 25, difficulty: "easy", equipment: ["olla", "sarten"],
    ingredients: [I("pasta", 200, "g"), I("panceta", 100, "g"), I("tomate-triturado", 300, "g"), I("chile", 1, "unit"), I("parmesano", 40, "g"), I("vino-blanco", 40, "ml"), I("sal", 12, "g")],
    steps: [
      S("Corta la panceta en tiras gruesas y dórala en una sartén fría a fuego medio 7 minutos, hasta que suelte la grasa y esté crujiente.", 7),
      S("Añade el chile, el vino y deja evaporar 1 minuto. Incorpora el tomate y cocina 12 minutos a fuego suave.", 13),
      S("Cuece la pasta al dente (unos 10 minutos) en agua con sal.", 10),
      S("Mezcla la pasta con la salsa 1 minuto, apaga el fuego y añade el queso rallado.", 1),
    ],
  }),
  r({
    id: "minestrone", title: "Minestrone", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia", note: "Sopa de verduras de temporada; cada casa la hace con lo que tiene.",
    baseServings: 4, prepMin: 20, cookMin: 40, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("zanahoria", 150, "g"), I("calabacin", 200, "g"), I("patata", 200, "g"), I("apio", 80, "g"), I("cebolla", 1, "unit"), I("tomate-triturado", 200, "g"), I("alubias-blancas", 400, "g"), I("pasta", 80, "g"), I("caldo", 1200, "ml"), I("aceite", 30, "ml"), I("parmesano", 30, "g", true), I("sal", 6, "g")],
    steps: [
      S("Corta todas las verduras en dados pequeños. Pocha la cebolla, la zanahoria y el apio en el aceite 8 minutos.", 8),
      S("Añade la patata, el calabacín y el tomate y rehoga 3 minutos.", 3),
      S("Cubre con el caldo y cocina 20 minutos a fuego medio.", 20),
      S("Añade las alubias escurridas y la pasta corta y cocina 9 minutos más. Sirve con parmesano rallado y un hilo de aceite.", 9),
    ],
  }),
  r({
    id: "tiramisu", title: "Tiramisú", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia (Véneto)", note: "Lleva huevo crudo: usa huevos muy frescos y consérvalo siempre en la nevera.",
    baseServings: 6, prepMin: 25, cookMin: 0, difficulty: "medium",
    ingredients: [I("mascarpone", 250, "g"), I("huevo", 3, "unit"), I("azucar", 75, "g"), I("bizcochos", 200, "g"), I("cafe", 15, "g"), I("cacao", 10, "g")],
    steps: [
      S("Prepara 300 ml de café fuerte y deja que se enfríe."),
      S("Bate las yemas con el azúcar hasta que blanqueen. Añade el mascarpone y mezcla hasta que quede liso."),
      S("Monta las claras a punto de nieve firme e incorpóralas a la crema con movimientos envolventes."),
      S("Moja los bizcochos en el café un segundo por cada lado y haz una capa en una fuente. Cubre con la mitad de la crema y repite."),
      S("Refrigera al menos 6 horas y espolvorea cacao justo antes de servir."),
    ],
  }),
  r({
    id: "ensalada-caprese", title: "Ensalada caprese", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia (Capri)", baseServings: 2, prepMin: 10, cookMin: 0, difficulty: "easy",
    ingredients: [I("tomate", 400, "g"), I("mozzarella", 250, "g"), I("albahaca", 10, "g"), I("aceite", 30, "ml"), I("sal", 2, "g"), I("pimienta", 1, "g")],
    steps: [
      S("Corta el tomate (mejor muy maduro y a temperatura ambiente) y la mozzarella en rodajas de 1 cm."),
      S("Alterna rodajas de tomate y mozzarella en un plato con hojas de albahaca."),
      S("Sala, añade pimienta y riega con un buen aceite de oliva justo antes de servir."),
    ],
  }),
  r({
    id: "focaccia", title: "Focaccia de romero y sal", cuisine: "italiana", authenticity: "adapted",
    origin: "Italia (Liguria)", note: "Se usa orégano seco en lugar de romero fresco.",
    baseServings: 6, prepMin: 25, cookMin: 25, difficulty: "medium", equipment: ["horno"],
    ingredients: [I("harina", 500, "g"), I("levadura", 7, "g"), I("aceite", 80, "ml"), I("sal", 12, "g"), I("oregano", 2, "g")],
    steps: [
      S("Mezcla la harina, la levadura, 10 g de sal, 40 ml de aceite y 380 ml de agua templada. Amasa 10 minutos: será una masa muy húmeda.", 10),
      S("Deja levar tapada 1 hora y media, hasta que doble su volumen."),
      S("Pásala a una bandeja aceitada y estírala con los dedos. Deja reposar 30 minutos más."),
      S("Precalienta el horno a 220 °C. Hunde los dedos en la masa para hacer hoyos, riega con el resto del aceite y espolvorea sal gruesa y orégano.", 15, 220),
      S("Hornea 22 minutos hasta que esté dorada por encima y suene hueca por debajo.", 22, 220),
    ],
  }),
  r({
    id: "espaguetis-vongole", title: "Espaguetis alle vongole", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia (Nápoles)", baseServings: 2, prepMin: 40, cookMin: 15, difficulty: "medium", equipment: ["olla", "sarten"],
    ingredients: [I("pasta", 200, "g"), I("almejas", 500, "g"), I("ajo", 3, "unit"), I("chile", 1, "unit"), I("vino-blanco", 80, "ml"), I("perejil", 15, "g"), I("aceite", 50, "ml"), I("sal", 10, "g")],
    steps: [
      S("Pon las almejas en agua fría con sal 30 minutos para que suelten la arena. Escúrrelas.", 30),
      S("Cuece la pasta 1 minuto menos de lo que indica el paquete.", 9),
      S("Mientras, dora el ajo laminado y el chile en el aceite 1 minuto. Añade las almejas y el vino, tapa y cocina 3 minutos hasta que se abran.", 4),
      S("Pasa la pasta a la sartén con un poco de agua de cocción y saltea 1 minuto para que absorba el jugo de las almejas. Termina con perejil.", 1),
    ],
  }),
  r({
    id: "pollo-cacciatore", title: "Pollo a la cazadora (cacciatore)", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia", baseServings: 4, prepMin: 15, cookMin: 50, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("pollo", 1000, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("champinones", 200, "g"), I("ajo", 2, "unit"), I("tomate-triturado", 400, "g"), I("vino-blanco", 150, "ml"), I("aceitunas", 60, "g"), I("oregano", 1, "g"), I("aceite", 40, "ml"), I("sal", 7, "g")],
    steps: [
      S("Sala el pollo troceado y dóralo en el aceite en una olla ancha 10 minutos. Resérvalo.", 10),
      S("En la misma olla, sofríe la cebolla, el pimiento, los champiñones y el ajo 8 minutos.", 8),
      S("Añade el vino y deja reducir 3 minutos. Incorpora el tomate y el orégano.", 3),
      S("Devuelve el pollo, tapa y cocina a fuego suave 25 minutos. Añade las aceitunas los últimos 5 minutos.", 25),
    ],
  }),
  r({
    id: "gnocchi-mantequilla", title: "Gnocchi de patata con mantequilla y parmesano", cuisine: "italiana", authenticity: "traditional",
    origin: "Italia", baseServings: 4, prepMin: 40, cookMin: 50, difficulty: "medium", equipment: ["olla", "sarten"],
    ingredients: [I("patata", 1000, "g"), I("harina", 250, "g"), I("huevo", 1, "unit"), I("mantequilla", 60, "g"), I("parmesano", 50, "g"), I("sal", 12, "g")],
    steps: [
      S("Cuece las patatas enteras con piel 35 minutos hasta que estén tiernas. Pélalas en caliente y aplástalas.", 35),
      S("Mezcla el puré templado con el huevo, 4 g de sal y la harina poco a poco, hasta tener una masa suave que no se pegue. No amases de más."),
      S("Haz cilindros de 2 cm, córtalos en trozos de 2 cm y márcalos con un tenedor."),
      S("Cuécelos en agua hirviendo con sal: están listos cuando suben a la superficie, unos 2 minutos.", 2),
      S("Saltéalos en la mantequilla derretida 2 minutos y sirve con parmesano.", 2),
    ],
  }),
  // ——— Francia ———
  r({
    id: "quiche-lorraine", title: "Quiche lorraine", cuisine: "francesa", authenticity: "traditional",
    origin: "Francia (Lorena)", baseServings: 6, prepMin: 20, cookMin: 45, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("masa-hojaldre", 275, "g"), I("panceta", 200, "g"), I("huevo", 4, "unit"), I("nata", 200, "ml"), I("leche", 200, "ml"), I("queso", 100, "g"), I("sal", 2, "g"), I("pimienta", 1, "g")],
    steps: [
      S("Precalienta el horno a 190 °C. Forra un molde con la masa, pínchala y hornéala 10 minutos con peso encima (garbanzos sobre papel).", 10, 190),
      S("Dora la panceta en tiras 6 minutos en una sartén sin aceite.", 6),
      S("Bate los huevos con la nata, la leche, la sal y la pimienta.", 2),
      S("Reparte la panceta y el queso rallado sobre la base, vierte la mezcla y hornea 30 minutos, hasta que esté cuajada y dorada.", 30, 190),
    ],
  }),
  r({
    id: "sopa-de-cebolla", title: "Sopa de cebolla gratinada", cuisine: "francesa", authenticity: "traditional",
    origin: "Francia (París)", baseServings: 4, prepMin: 15, cookMin: 70, difficulty: "medium", equipment: ["olla", "horno"],
    ingredients: [I("cebolla", 5, "unit"), I("mantequilla", 50, "g"), I("harina", 15, "g"), I("vino-blanco", 150, "ml"), I("caldo", 1000, "ml"), I("pan", 150, "g"), I("queso", 150, "g"), I("sal", 5, "g")],
    steps: [
      S("Corta las cebollas en juliana fina. Cocínalas en la mantequilla a fuego bajo 40 minutos, removiendo de vez en cuando, hasta que estén muy blandas y color caramelo.", 40),
      S("Añade la harina y remueve 1 minuto. Vierte el vino y deja reducir 2 minutos.", 3),
      S("Añade el caldo y la sal y cocina 15 minutos.", 15),
      S("Reparte en cuencos aptos para horno, coloca encima pan tostado y abundante queso rallado y gratina 6 minutos a 230 °C, hasta que burbujee.", 6, 230),
    ],
  }),
  r({
    id: "croque-monsieur", title: "Croque monsieur", cuisine: "francesa", authenticity: "traditional",
    origin: "Francia (París)", baseServings: 2, prepMin: 10, cookMin: 15, difficulty: "easy", equipment: ["horno", "olla"],
    ingredients: [I("pan", 200, "g"), I("jamon", 100, "g"), I("queso", 120, "g"), I("mantequilla", 30, "g"), I("harina", 15, "g"), I("leche", 150, "ml"), I("sal", 1, "g")],
    steps: [
      S("Prepara una bechamel rápida: funde 15 g de mantequilla, tuesta la harina 1 minuto y añade la leche removiendo 3 minutos hasta que espese.", 4),
      S("Unta 4 rebanadas de pan con el resto de mantequilla por fuera."),
      S("Monta los sándwiches con jamón, queso y un poco de bechamel dentro. Cubre por encima con bechamel y queso rallado."),
      S("Gratina en el horno a 220 °C 8 minutos, hasta que el queso esté dorado y burbujeante.", 8, 220),
    ],
  }),
  r({
    id: "boeuf-bourguignon", title: "Ternera a la borgoñona (bœuf bourguignon)", cuisine: "francesa", authenticity: "adapted",
    origin: "Francia (Borgoña)", note: "Se hace con vino de Borgoña y carne de guiso. Sin cebollitas perla.",
    baseServings: 6, prepMin: 25, cookMin: 165, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("ternera", 1200, "g"), I("panceta", 150, "g"), I("vino-tinto", 600, "ml"), I("caldo", 300, "ml"), I("cebolla", 2, "unit"), I("zanahoria", 300, "g"), I("champinones", 250, "g"), I("ajo", 3, "unit"), I("harina", 30, "g"), I("mantequilla", 30, "g"), I("aceite", 30, "ml"), I("sal", 9, "g")],
    steps: [
      S("Corta la carne en dados de 5 cm, sécala y sálala. Dora la panceta en una olla grande 5 minutos y retírala.", 5),
      S("Dora la carne en tandas en esa grasa con el aceite, 3 minutos por lado, sin amontonarla. Retírala.", 15),
      S("Rehoga la cebolla, la zanahoria y el ajo 8 minutos. Añade la harina y remueve 1 minuto.", 9),
      S("Devuelve carne y panceta, vierte el vino y el caldo y cocina tapado a fuego muy suave 2 horas, hasta que la carne esté tierna.", 120),
      S("Saltea los champiñones en la mantequilla 6 minutos y añádelos al guiso los últimos 10 minutos.", 16),
    ],
  }),
  r({
    id: "gratin-dauphinois", title: "Gratin dauphinois", cuisine: "francesa", authenticity: "traditional",
    origin: "Francia (Delfinado)", baseServings: 6, prepMin: 20, cookMin: 75, difficulty: "easy", equipment: ["horno", "olla"],
    ingredients: [I("patata", 1200, "g"), I("nata", 400, "ml"), I("leche", 300, "ml"), I("ajo", 2, "unit"), I("mantequilla", 20, "g"), I("sal", 8, "g"), I("pimienta", 1, "g")],
    steps: [
      S("Precalienta el horno a 160 °C. Pela las patatas y córtalas en láminas de 3 mm (sin lavarlas: el almidón espesa la crema).", 10, 160),
      S("Calienta la nata y la leche con el ajo aplastado, la sal y la pimienta. Añade las patatas y cocina 10 minutos a fuego suave, removiendo con cuidado.", 10),
      S("Unta una fuente con mantequilla y vierte las patatas con su crema, alisando la superficie."),
      S("Hornea 60 minutos hasta que la superficie esté dorada y un cuchillo atraviese las patatas sin resistencia. Reposa 10 minutos.", 60, 160),
    ],
  }),
  r({
    id: "mousse-chocolate", title: "Mousse de chocolate", cuisine: "francesa", authenticity: "traditional",
    origin: "Francia", note: "Lleva huevo crudo: usa huevos muy frescos y mantenla en frío.",
    baseServings: 4, prepMin: 20, cookMin: 5, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("chocolate", 200, "g"), I("huevo", 4, "unit"), I("azucar", 30, "g"), I("mantequilla", 30, "g"), I("sal", 1, "g")],
    steps: [
      S("Funde el chocolate con la mantequilla al baño maría a fuego bajo, removiendo, 5 minutos. Deja templar.", 5),
      S("Añade las yemas una a una al chocolate, mezclando bien."),
      S("Monta las claras con la sal y, cuando estén espumosas, añade el azúcar y bate hasta punto de nieve firme."),
      S("Incorpora las claras al chocolate en tres veces con movimientos envolventes, sin batir. Reparte en vasitos y refrigera al menos 4 horas."),
    ],
  }),
  r({
    id: "tarta-tatin", title: "Tarta tatin", cuisine: "francesa", authenticity: "traditional",
    origin: "Francia (Sologne)", note: "Se hornea al revés y se desmolda en caliente.",
    baseServings: 6, prepMin: 20, cookMin: 45, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("manzana", 6, "unit"), I("masa-hojaldre", 275, "g"), I("azucar", 120, "g"), I("mantequilla", 60, "g")],
    steps: [
      S("Precalienta el horno a 200 °C. Pela las manzanas y córtalas en cuartos sin el corazón.", 10, 200),
      S("En una sartén apta para horno, funde el azúcar con la mantequilla a fuego medio 6 minutos hasta tener un caramelo dorado.", 6),
      S("Coloca las manzanas apretadas sobre el caramelo y cocina 10 minutos a fuego medio para que se caramelicen.", 10),
      S("Cubre con la masa, mete los bordes hacia dentro y pincha la superficie. Hornea 25 minutos hasta que la masa esté dorada.", 25, 200),
      S("Espera 2 minutos y dale la vuelta sobre un plato con un movimiento decidido (con guantes: el caramelo quema)."),
    ],
  }),
  // ——— Alemania ———
  r({
    id: "schnitzel", title: "Schnitzel de cerdo", cuisine: "alemana", authenticity: "adapted",
    origin: "Alemania y Austria", note: "El Wiener Schnitzel auténtico es de ternera; el de cerdo es el más común en Alemania.",
    baseServings: 2, prepMin: 15, cookMin: 10, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("cerdo", 300, "g"), I("harina", 40, "g"), I("huevo", 2, "unit"), I("pan-rallado", 80, "g"), I("limon", 1, "unit"), I("aceite", 300, "ml"), I("sal", 3, "g")],
    steps: [
      S("Corta el lomo en filetes y aplánalos entre dos papeles hasta 4 mm. Sálalos."),
      S("Pásalos por harina, huevo batido y pan rallado, sin apretar: el rebozado debe quedar suelto."),
      S("Fríe en abundante aceite a 170 °C, moviendo la sartén para que el aceite cubra la parte de arriba, 2 minutos por lado. El rebozado se infla y ondula.", 4, 170),
      S("Escurre y sirve con gajos de limón y ensalada de patata."),
    ],
  }),
  r({
    id: "kartoffelsalat", title: "Ensalada alemana de patata", cuisine: "alemana", authenticity: "traditional",
    origin: "Alemania (sur)", note: "La versión del sur se aliña con caldo y vinagre en caliente, sin mayonesa.",
    baseServings: 4, prepMin: 15, cookMin: 25, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("patata", 1000, "g"), I("cebolla", 1, "unit"), I("caldo", 200, "ml"), I("vinagre", 50, "ml"), I("mostaza", 15, "g"), I("aceite", 50, "ml"), I("panceta", 100, "g", true), I("sal", 6, "g"), I("pimienta", 1, "g")],
    steps: [
      S("Cuece las patatas con piel 22 minutos hasta que estén tiernas. Pélalas en caliente y córtalas en rodajas finas.", 22),
      S("Calienta el caldo con la cebolla picada fina, el vinagre, la mostaza, la sal y la pimienta 3 minutos.", 3),
      S("Vierte el aliño caliente sobre las patatas, mezcla con cuidado y deja que lo absorban 15 minutos. Añade el aceite.", 15),
      S("Si quieres, dora la panceta en dados y añádela por encima. Se sirve templada."),
    ],
  }),
  r({
    id: "apfelstrudel", title: "Strudel de manzana", cuisine: "alemana", authenticity: "adapted",
    origin: "Austria y Alemania", note: "Se usa hojaldre en lugar de la masa de strudel estirada a mano.",
    baseServings: 6, prepMin: 25, cookMin: 35, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("masa-hojaldre", 275, "g"), I("manzana", 4, "unit"), I("azucar", 70, "g"), I("canela", 4, "g"), I("nueces", 50, "g"), I("pan-rallado", 30, "g"), I("mantequilla", 40, "g"), I("limon", 0.5, "unit"), I("huevo", 1, "unit")],
    steps: [
      S("Precalienta el horno a 200 °C. Tuesta el pan rallado en la mantequilla 3 minutos.", 3, 200),
      S("Pela y lamina las manzanas. Mézclalas con el azúcar, la canela, las nueces picadas y el zumo de limón."),
      S("Extiende la masa, reparte el pan rallado en la mitad inferior y la manzana encima. Enrolla y cierra los extremos."),
      S("Pinta con huevo batido, haz unos cortes en la superficie y hornea 30 minutos hasta que esté dorado.", 30, 200),
    ],
  }),
  // ——— Reino Unido ———
  r({
    id: "fish-and-chips", title: "Fish and chips", cuisine: "britanica", authenticity: "adapted",
    origin: "Reino Unido", note: "El rebozado tradicional lleva cerveza; aquí, agua muy fría con levadura.",
    baseServings: 4, prepMin: 30, cookMin: 30, difficulty: "medium", equipment: ["sarten"],
    ingredients: [I("merluza", 600, "g"), I("patata", 1000, "g"), I("harina", 200, "g"), I("levadura", 3, "g"), I("aceite", 600, "ml"), I("limon", 1, "unit"), I("vinagre", 30, "ml", true), I("sal", 8, "g")],
    steps: [
      S("Mezcla la harina, la levadura, una pizca de sal y 250 ml de agua muy fría hasta una masa espesa. Deja reposar 20 minutos.", 20),
      S("Corta las patatas en bastones gruesos y fríelas a 150 °C 8 minutos sin dorar. Sácalas.", 8, 150),
      S("Seca y sala el pescado en trozos grandes. Pásalo por harina, luego por la masa, y fríelo a 180 °C 5 minutos hasta que esté dorado.", 5, 180),
      S("Vuelve a freír las patatas a 190 °C 3 minutos hasta que estén crujientes.", 3, 190),
      S("Sirve con sal, limón y unas gotas de vinagre, como en Inglaterra."),
    ],
  }),
  r({
    id: "cottage-pie", title: "Pastel de carne con puré (cottage pie)", cuisine: "britanica", authenticity: "traditional",
    origin: "Reino Unido", note: "Con ternera es cottage pie; con cordero se llama shepherd's pie.",
    baseServings: 6, prepMin: 25, cookMin: 60, difficulty: "easy", equipment: ["horno", "olla", "sarten"],
    ingredients: [I("ternera-picada", 600, "g"), I("cebolla", 1, "unit"), I("zanahoria", 200, "g"), I("guisantes", 150, "g"), I("tomate-triturado", 150, "g"), I("caldo", 250, "ml"), I("patata", 1000, "g"), I("mantequilla", 50, "g"), I("leche", 150, "ml"), I("queso", 60, "g", true), I("aceite", 20, "ml"), I("sal", 9, "g")],
    steps: [
      S("Cuece las patatas peladas 20 minutos. Escúrrelas y haz un puré con la mantequilla, la leche y sal.", 20),
      S("Sofríe la cebolla y la zanahoria picadas 8 minutos. Añade la carne y dórala 8 minutos.", 16),
      S("Agrega el tomate y el caldo y cocina 10 minutos. Añade los guisantes al final.", 10),
      S("Precalienta el horno a 200 °C. Pon la carne en una fuente, cubre con el puré, marca rayas con un tenedor y espolvorea queso.", 10, 200),
      S("Hornea 25 minutos hasta que el puré esté dorado.", 25, 200),
    ],
  }),
  r({
    id: "desayuno-ingles", title: "Desayuno inglés", cuisine: "britanica", authenticity: "adapted",
    origin: "Reino Unido", note: "Sin morcilla inglesa ni baked beans en lata: se hacen alubias en tomate.",
    baseServings: 2, prepMin: 10, cookMin: 20, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("huevo", 4, "unit"), I("salchichas", 200, "g"), I("panceta", 100, "g"), I("alubias-blancas", 200, "g"), I("tomate-triturado", 100, "g"), I("champinones", 150, "g"), I("tomate", 200, "g"), I("pan", 100, "g"), I("aceite", 20, "ml"), I("sal", 2, "g")],
    steps: [
      S("Dora las salchichas en una sartén a fuego medio 10 minutos, girándolas.", 10),
      S("Calienta las alubias con el tomate triturado y una pizca de azúcar 5 minutos.", 5),
      S("En la misma sartén, dora la panceta 3 minutos, los champiñones 4 minutos y el tomate partido por la mitad 2 minutos por cara.", 9),
      S("Fríe los huevos y tuesta el pan. Sirve todo junto en el plato.", 3),
    ],
  }),
  r({
    id: "crumble-manzana", title: "Crumble de manzana", cuisine: "britanica", authenticity: "traditional",
    origin: "Reino Unido", baseServings: 6, prepMin: 15, cookMin: 35, difficulty: "easy", equipment: ["horno"],
    ingredients: [I("manzana", 5, "unit"), I("azucar", 120, "g"), I("canela", 3, "g"), I("harina", 150, "g"), I("mantequilla", 100, "g"), I("limon", 0.5, "unit")],
    steps: [
      S("Precalienta el horno a 190 °C. Pela las manzanas, córtalas en dados y mézclalas con 40 g de azúcar, la canela y el zumo de limón.", 10, 190),
      S("Pon las manzanas en una fuente."),
      S("Frota con las yemas de los dedos la harina, el resto del azúcar y la mantequilla fría en dados hasta tener unas migas gruesas."),
      S("Reparte las migas sobre la fruta y hornea 35 minutos hasta que estén doradas y la fruta burbujee por los bordes.", 35, 190),
    ],
  }),
  // ——— Grecia ———
  r({
    id: "spanakopita", title: "Spanakopita (empanada de espinacas y feta)", cuisine: "griega", authenticity: "adapted",
    origin: "Grecia", note: "Se hace con masa filo; aquí, con hojaldre, que es más fácil de encontrar.",
    baseServings: 6, prepMin: 25, cookMin: 40, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("masa-hojaldre", 550, "g"), I("espinacas", 600, "g"), I("feta", 200, "g"), I("huevo", 2, "unit"), I("cebolleta", 3, "unit"), I("perejil", 15, "g"), I("aceite", 30, "ml"), I("pimienta", 1, "g")],
    steps: [
      S("Saltea la cebolleta picada en el aceite 3 minutos. Añade las espinacas y cocina 5 minutos hasta que pierdan el agua. Escúrrelas muy bien.", 8),
      S("Mezcla las espinacas con la feta desmenuzada, un huevo, el perejil y la pimienta (no hace falta sal: la feta es salada)."),
      S("Precalienta el horno a 190 °C. Forra un molde con una lámina de masa, rellena y cubre con la otra. Sella los bordes.", 10, 190),
      S("Pinta con el otro huevo, marca porciones con un cuchillo y hornea 35 minutos hasta que esté dorada.", 35, 190),
    ],
  }),
  r({
    id: "gemista", title: "Gemista (verduras rellenas de arroz)", cuisine: "griega", authenticity: "traditional",
    origin: "Grecia", baseServings: 4, prepMin: 30, cookMin: 70, difficulty: "medium", equipment: ["horno"],
    ingredients: [I("tomate", 800, "g"), I("pimiento", 3, "unit"), I("arroz", 150, "g"), I("cebolla", 1, "unit"), I("ajo", 2, "unit"), I("perejil", 15, "g"), I("menta", 10, "g", true), I("patata", 400, "g"), I("aceite", 80, "ml"), I("sal", 8, "g")],
    steps: [
      S("Corta la tapa de los tomates y pimientos y vacíalos. Tritura la pulpa de los tomates."),
      S("Mezcla el arroz crudo con la pulpa, la cebolla y el ajo picados, las hierbas, la mitad del aceite y sal."),
      S("Precalienta el horno a 190 °C. Rellena las verduras hasta tres cuartos (el arroz crece) y tápalas con su sombrero.", 10, 190),
      S("Colócalas en una fuente con la patata en gajos entre ellas, riega con el resto de aceite y un vaso de agua. Hornea 60 minutos hasta que el arroz esté tierno.", 60, 190),
    ],
  }),
  r({
    id: "fasolada", title: "Fasolada (sopa griega de alubias)", cuisine: "griega", authenticity: "traditional",
    origin: "Grecia", note: "Considerada a menudo el plato nacional griego.",
    baseServings: 4, prepMin: 15, cookMin: 40, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("alubias-blancas", 800, "g"), I("zanahoria", 200, "g"), I("apio", 100, "g"), I("cebolla", 1, "unit"), I("tomate-triturado", 200, "g"), I("caldo", 800, "ml"), I("aceite", 80, "ml"), I("limon", 1, "unit"), I("sal", 6, "g")],
    steps: [
      S("Pica la cebolla, la zanahoria y el apio y pochalos en la mitad del aceite 10 minutos.", 10),
      S("Añade el tomate y cocina 5 minutos.", 5),
      S("Agrega las alubias escurridas y el caldo y cocina a fuego suave 25 minutos, hasta que la sopa espese.", 25),
      S("Apaga, añade el resto del aceite crudo y sirve con limón."),
    ],
  }),
  // ——— Turquía ———
  r({
    id: "mercimek-corbasi", title: "Sopa turca de lentejas (mercimek çorbası)", cuisine: "turca", authenticity: "adapted",
    origin: "Turquía", note: "Se hace con lentejas rojas, que se deshacen y dan una crema. Con pardinas hay que triturar más tiempo.",
    baseServings: 4, prepMin: 10, cookMin: 35, difficulty: "easy", equipment: ["olla", "batidora"],
    ingredients: [I("lentejas", 250, "g"), I("cebolla", 1, "unit"), I("zanahoria", 150, "g"), I("patata", 150, "g"), I("comino", 3, "g"), I("pimenton", 4, "g"), I("caldo", 1200, "ml"), I("mantequilla", 30, "g"), I("limon", 1, "unit"), I("sal", 6, "g")],
    steps: [
      S("Pocha la cebolla, la zanahoria y la patata picadas en la mitad de la mantequilla 6 minutos.", 6),
      S("Añade las lentejas lavadas, el comino y el caldo. Cocina 25 minutos hasta que todo esté muy tierno.", 25),
      S("Tritura hasta obtener una crema fina y ajusta de sal.", 2),
      S("Funde el resto de mantequilla con el pimentón 30 segundos y viértelo por encima. Sirve con limón.", 1),
    ],
  }),
  r({
    id: "imam-bayildi", title: "Imam bayildi (berenjenas rellenas)", cuisine: "turca", authenticity: "traditional",
    origin: "Turquía", note: "Su nombre significa «el imán se desmayó». Se sirve templada o fría.",
    baseServings: 4, prepMin: 20, cookMin: 50, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("berenjena", 800, "g"), I("cebolla", 2, "unit"), I("tomate", 400, "g"), I("ajo", 4, "unit"), I("perejil", 20, "g"), I("azucar", 5, "g"), I("aceite", 100, "ml"), I("sal", 7, "g")],
    steps: [
      S("Pela las berenjenas a tiras y fríelas enteras en la mitad del aceite 8 minutos, girándolas, hasta que se ablanden.", 8),
      S("Sofríe la cebolla en juliana y el ajo en el resto del aceite 12 minutos. Añade el tomate picado, el azúcar y la sal y cocina 8 minutos. Agrega el perejil.", 20),
      S("Precalienta el horno a 180 °C. Abre las berenjenas a lo largo y rellénalas con el sofrito.", 10, 180),
      S("Colócalas en una fuente con un poco de agua y hornea 30 minutos.", 30, 180),
    ],
  }),
  r({
    id: "lahmacun", title: "Lahmacun (pizza turca de carne)", cuisine: "turca", authenticity: "adapted",
    origin: "Turquía", note: "Masa muy fina, horno al máximo. Se come enrollada con perejil y limón.",
    baseServings: 4, prepMin: 90, cookMin: 20, difficulty: "medium", equipment: ["horno", "batidora"],
    ingredients: [I("harina", 300, "g"), I("levadura", 4, "g"), I("ternera-picada", 300, "g"), I("tomate", 200, "g"), I("pimiento", 1, "unit"), I("cebolla", 1, "unit"), I("ajo", 2, "unit"), I("pimenton", 6, "g"), I("perejil", 20, "g"), I("limon", 1, "unit"), I("aceite", 20, "ml"), I("sal", 8, "g")],
    steps: [
      S("Mezcla la harina, la levadura, 5 g de sal, el aceite y 180 ml de agua templada. Amasa 8 minutos y deja levar 1 hora.", 68),
      S("Tritura el tomate, el pimiento, la cebolla, el ajo, la mitad del perejil, el pimentón y la sal restante. Mézclalo con la carne cruda.", 3),
      S("Precalienta el horno a 250 °C con la bandeja dentro. Divide la masa en 4 y estira cada bola muy fina.", 15, 250),
      S("Extiende una capa fina de carne y hornea cada lahmacun 6 minutos sobre la bandeja caliente.", 6, 250),
      S("Sirve con perejil y limón, y enróllalo para comerlo."),
    ],
  }),
];
