import type { Recipe } from "@comocomo/schemas";
import { I, r, S } from "./helpers";

/** Lote 4D: América, África y Oriente Medio, más algunos clásicos caseros. Recetas escritas para COMOCOMO. */
export const recipesAmericaAfrica: Recipe[] = [
  // ——— México ———
  r({
    id: "pozole-rojo", title: "Pozole rojo", cuisine: "mexicana", authenticity: "adapted",
    origin: "México (Jalisco)", note: "Se hace con maíz cacahuazintle (nixtamalizado); el maíz dulce en lata es un sustituto aproximado.",
    baseServings: 6, prepMin: 20, cookMin: 100, difficulty: "medium", equipment: ["olla", "batidora"],
    ingredients: [I("cerdo", 800, "g"), I("maiz", 560, "g"), I("chile", 4, "unit"), I("pimenton", 10, "g"), I("ajo", 4, "unit"), I("cebolla", 1, "unit"), I("oregano", 3, "g"), I("lechuga", 1, "unit"), I("lima", 3, "unit"), I("sal", 10, "g")],
    steps: [
      S("Cuece el cerdo en trozos grandes con media cebolla, 2 ajos y sal en 3 litros de agua, retirando la espuma, durante 80 minutos.", 80),
      S("Tritura los chiles y el pimentón con el resto del ajo y un cazo de caldo, y cuela la salsa.", 3),
      S("Añade la salsa y el maíz escurrido a la olla y cocina 15 minutos más.", 15),
      S("Deshilacha la carne dentro del caldo. Sirve con lechuga picada, cebolla, orégano y lima para que cada uno se ponga al gusto."),
    ],
  }),
  r({
    id: "cochinita-pibil", title: "Cochinita pibil", cuisine: "mexicana", authenticity: "adapted",
    origin: "México (Yucatán)", note: "Lleva achiote y naranja agria y se cocina enterrada en hojas de plátano. Aquí, pimentón, naranja y lima al horno.",
    baseServings: 6, prepMin: 140, cookMin: 150, difficulty: "medium", equipment: ["horno", "batidora"],
    ingredients: [I("cerdo", 1200, "g"), I("naranja", 3, "unit"), I("lima", 2, "unit"), I("pimenton", 15, "g"), I("ajo", 4, "unit"), I("comino", 3, "g"), I("oregano", 2, "g"), I("vinagre", 30, "ml"), I("cebolla", 1, "unit"), I("tortilla-maiz", 18, "unit"), I("sal", 10, "g")],
    steps: [
      S("Tritura el zumo de las naranjas y una lima con el pimentón, el ajo, el comino, el orégano, el vinagre y la sal.", 2),
      S("Corta el cerdo en trozos grandes, cúbrelo con la marinada y déjalo al menos 2 horas en la nevera (mejor toda la noche).", 120),
      S("Precalienta el horno a 160 °C. Pon la carne con la marinada en una fuente, tapa con papel de aluminio y hornea 2 horas y media, hasta que se deshaga.", 150, 160),
      S("Corta la cebolla en plumas finas y cúbrela con el zumo de la otra lima y sal: es la cebolla encurtida."),
      S("Deshilacha la carne en su jugo y sírvela en tortillas calientes con la cebolla encurtida."),
    ],
  }),
  r({
    id: "sopa-de-tortilla", title: "Sopa de tortilla", cuisine: "mexicana", authenticity: "adapted",
    origin: "México (Ciudad de México)", note: "Se acompaña de chile pasilla y queso fresco; aquí, chile fresco y queso para fundir.",
    baseServings: 4, prepMin: 15, cookMin: 30, difficulty: "easy", equipment: ["olla", "sarten", "batidora"],
    ingredients: [I("tortilla-maiz", 8, "unit"), I("tomate", 500, "g"), I("cebolla", 0.5, "unit"), I("ajo", 2, "unit"), I("chile", 1, "unit"), I("caldo", 1000, "ml"), I("aguacate", 1, "unit"), I("queso", 100, "g"), I("nata", 100, "ml", true), I("aceite", 200, "ml"), I("sal", 5, "g")],
    steps: [
      S("Corta las tortillas en tiras y fríelas en el aceite 2 minutos hasta que estén crujientes. Escúrrelas.", 2),
      S("Tritura el tomate con la cebolla, el ajo y el chile. Fríe la salsa en 2 cucharadas de aceite 6 minutos.", 6),
      S("Añade el caldo y la sal y cocina 15 minutos.", 15),
      S("Sirve el caldo bien caliente sobre las tiras de tortilla, con aguacate en dados, queso y un poco de nata."),
    ],
  }),
  r({
    id: "frijoles-charros", title: "Frijoles charros", cuisine: "mexicana", authenticity: "adapted",
    origin: "México (norte)", note: "Se hacen con frijol pinto; con frijol negro de bote quedan muy bien.",
    baseServings: 4, prepMin: 10, cookMin: 30, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("frijoles-negros", 800, "g"), I("panceta", 100, "g"), I("chorizo", 100, "g"), I("tomate", 200, "g"), I("cebolla", 1, "unit"), I("chile", 2, "unit"), I("ajo", 2, "unit"), I("cilantro", 10, "g"), I("sal", 3, "g")],
    steps: [
      S("Dora la panceta y el chorizo en dados en una olla 6 minutos, hasta que suelten la grasa.", 6),
      S("Añade la cebolla, el ajo y el chile picados y sofríe 5 minutos. Agrega el tomate picado y cocina 5 minutos.", 10),
      S("Incorpora los frijoles con un poco de su líquido y 300 ml de agua. Cocina 15 minutos a fuego suave.", 15),
      S("Termina con cilantro picado. Se sirven caldosos, como acompañamiento o en tacos."),
    ],
  }),
  r({
    id: "burritos-ternera", title: "Burritos de ternera y frijoles", cuisine: "mexicana", authenticity: "adapted",
    origin: "México (norte) y EE. UU.", baseServings: 4, prepMin: 15, cookMin: 25, difficulty: "easy", equipment: ["sarten", "olla"],
    ingredients: [I("tortilla-trigo", 4, "unit"), I("ternera-picada", 400, "g"), I("frijoles-negros", 400, "g"), I("arroz", 150, "g"), I("cebolla", 1, "unit"), I("tomate", 200, "g"), I("queso", 120, "g"), I("comino", 3, "g"), I("pimenton", 5, "g"), I("lechuga", 1, "unit", true), I("aceite", 20, "ml"), I("sal", 5, "g")],
    steps: [
      S("Cuece el arroz 15 minutos en agua con sal.", 15),
      S("Sofríe la cebolla en el aceite 5 minutos. Añade la carne, el comino, el pimentón y la sal y cocina 8 minutos. Agrega el tomate picado 3 minutos.", 16),
      S("Calienta los frijoles y aplástalos un poco.", 3),
      S("Calienta las tortillas 20 segundos por lado. Rellena con arroz, frijoles, carne, queso y lechuga, dobla los lados y enrolla apretando."),
    ],
  }),
  r({
    id: "fajitas-pollo", title: "Fajitas de pollo", cuisine: "mexicana", authenticity: "adapted",
    origin: "México y Texas", baseServings: 3, prepMin: 20, cookMin: 15, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("pollo", 500, "g"), I("pimiento", 2, "unit"), I("cebolla", 1, "unit"), I("tortilla-trigo", 6, "unit"), I("lima", 1, "unit"), I("comino", 3, "g"), I("pimenton", 5, "g"), I("ajo", 2, "unit"), I("aguacate", 1, "unit", true), I("aceite", 30, "ml"), I("sal", 5, "g")],
    steps: [
      S("Corta el pollo en tiras y marínalo con el zumo de lima, el comino, el pimentón, el ajo rallado, la sal y la mitad del aceite 10 minutos.", 10),
      S("Saltea los pimientos y la cebolla en tiras en el resto del aceite a fuego fuerte 5 minutos. Resérvalos.", 5),
      S("Saltea el pollo a fuego fuerte 6 minutos hasta que esté dorado. Junta con las verduras 1 minuto.", 7),
      S("Calienta las tortillas y sirve todo en la mesa para que cada uno se monte sus fajitas, con aguacate.", 2),
    ],
  }),
  r({
    id: "arroz-mexicano", title: "Arroz a la mexicana", cuisine: "mexicana", authenticity: "traditional",
    origin: "México", baseServings: 4, prepMin: 10, cookMin: 30, difficulty: "easy", equipment: ["olla", "batidora"],
    ingredients: [I("arroz", 300, "g"), I("tomate", 300, "g"), I("cebolla", 0.5, "unit"), I("ajo", 2, "unit"), I("caldo", 600, "ml"), I("zanahoria", 100, "g"), I("guisantes", 100, "g"), I("aceite", 40, "ml"), I("sal", 5, "g")],
    steps: [
      S("Tritura el tomate con la cebolla y el ajo.", 1),
      S("Fríe el arroz en el aceite a fuego medio 5 minutos, removiendo, hasta que esté dorado y suene seco.", 5),
      S("Añade el tomate triturado y cocina 3 minutos. Agrega el caldo caliente, la zanahoria en dados, los guisantes y la sal.", 3),
      S("Cuando hierva, tapa y cocina a fuego bajo 18 minutos sin destapar. Deja reposar 5 minutos y suelta el arroz con un tenedor.", 23),
    ],
  }),
  // ——— Estados Unidos ———
  r({
    id: "tortitas-americanas", title: "Tortitas americanas (pancakes)", cuisine: "estadounidense", authenticity: "traditional",
    origin: "Estados Unidos", note: "Salen unas 10. Se sirven con mantequilla y sirope de arce o miel.",
    baseServings: 3, prepMin: 10, cookMin: 15, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("harina", 200, "g"), I("levadura-quimica", 8, "g"), I("huevo", 1, "unit"), I("leche", 300, "ml"), I("mantequilla", 30, "g"), I("azucar", 20, "g"), I("miel", 60, "g", true), I("sal", 1, "g")],
    steps: [
      S("Mezcla la harina, la levadura, el azúcar y la sal. En otro bol, bate el huevo con la leche y la mantequilla derretida."),
      S("Junta ambas mezclas sin batir de más: está bien que queden algunos grumos. Así salen esponjosas."),
      S("Calienta una sartén a fuego medio, úntala con un poco de mantequilla y vierte un cazo de masa.", 1),
      S("Cuando salgan burbujas en la superficie (unos 2 minutos), dales la vuelta y cocina 1 minuto más. Repite con el resto.", 12),
    ],
  }),
  r({
    id: "brownies", title: "Brownies de chocolate y nueces", cuisine: "estadounidense", authenticity: "traditional",
    origin: "Estados Unidos", note: "Están en su punto cuando el centro aún tiembla un poco al sacarlos.",
    baseServings: 8, prepMin: 15, cookMin: 25, difficulty: "easy", equipment: ["horno", "olla"],
    ingredients: [I("chocolate", 200, "g"), I("mantequilla", 150, "g"), I("azucar", 200, "g"), I("huevo", 3, "unit"), I("harina", 100, "g"), I("nueces", 80, "g"), I("sal", 1, "g")],
    steps: [
      S("Precalienta el horno a 180 °C y forra un molde cuadrado de 20 cm con papel.", 10, 180),
      S("Funde el chocolate con la mantequilla al baño maría. Fuera del fuego, añade el azúcar y luego los huevos uno a uno.", 5),
      S("Incorpora la harina, la sal y las nueces troceadas, mezclando lo justo."),
      S("Vierte en el molde y hornea 22 minutos. Deja enfriar del todo antes de cortar en cuadrados.", 22, 180),
    ],
  }),
  r({
    id: "chili-con-carne", title: "Chili con carne", cuisine: "estadounidense", authenticity: "adapted",
    origin: "Estados Unidos (Texas)", note: "En Texas el chili no lleva alubias; la versión con alubias es la más extendida fuera.",
    baseServings: 4, prepMin: 15, cookMin: 50, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("ternera-picada", 500, "g"), I("frijoles-negros", 400, "g"), I("tomate-triturado", 400, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("ajo", 3, "unit"), I("chile", 2, "unit"), I("comino", 5, "g"), I("pimenton", 8, "g"), I("oregano", 2, "g"), I("arroz", 240, "g", true), I("aceite", 30, "ml"), I("sal", 6, "g")],
    steps: [
      S("Sofríe la cebolla, el pimiento, el ajo y el chile picados en el aceite 8 minutos.", 8),
      S("Añade la carne y dórala 8 minutos deshaciéndola. Agrega el comino, el pimentón y el orégano 1 minuto.", 9),
      S("Incorpora el tomate, la sal y 200 ml de agua y cocina tapado a fuego suave 25 minutos.", 25),
      S("Añade los frijoles escurridos y cocina 8 minutos más. Sirve con arroz, nata o queso rallado.", 8),
    ],
  }),
  r({
    id: "costillas-bbq", title: "Costillas de cerdo a la barbacoa", cuisine: "estadounidense", authenticity: "adapted",
    origin: "Estados Unidos", note: "Al horno, cocción lenta y glaseado al final; la salsa barbacoa es casera.",
    baseServings: 4, prepMin: 15, cookMin: 165, difficulty: "easy", equipment: ["horno", "olla"],
    ingredients: [I("costillas-cerdo", 1600, "g"), I("tomate-triturado", 200, "g"), I("miel", 60, "g"), I("vinagre", 40, "ml"), I("azucar", 30, "g"), I("pimenton", 10, "g"), I("ajo", 3, "unit"), I("mostaza", 15, "g"), I("sal", 10, "g")],
    steps: [
      S("Precalienta el horno a 150 °C. Frota las costillas con sal, la mitad del pimentón y el ajo rallado.", 10, 150),
      S("Envuélvelas en papel de aluminio y hornea 2 horas, hasta que la carne se separe del hueso.", 120, 150),
      S("Para la salsa, cocina el tomate, la miel, el vinagre, el azúcar, la mostaza y el resto del pimentón 15 minutos hasta que espese.", 15),
      S("Abre el papel, pinta las costillas con la salsa y gratínalas a 220 °C 15 minutos, pintando de nuevo a mitad, hasta que estén caramelizadas.", 15, 220),
    ],
  }),
  r({
    id: "cheesecake", title: "Cheesecake al horno", cuisine: "estadounidense", authenticity: "traditional",
    origin: "Estados Unidos (Nueva York)", note: "Necesita enfriarse en la nevera varias horas antes de cortarla.",
    baseServings: 8, prepMin: 20, cookMin: 70, difficulty: "medium", equipment: ["horno"],
    ingredients: [I("galletas", 200, "g"), I("mantequilla", 80, "g"), I("queso-crema", 600, "g"), I("azucar", 180, "g"), I("huevo", 3, "unit"), I("nata", 200, "ml"), I("harina", 20, "g"), I("limon", 1, "unit")],
    steps: [
      S("Precalienta el horno a 170 °C. Machaca las galletas hasta dejarlas en migas (en una bolsa con un rodillo o con la batidora), mézclalas con la mantequilla derretida y presiona en la base de un molde desmontable.", 10, 170),
      S("Bate el queso crema con el azúcar y la ralladura de limón. Añade los huevos de uno en uno, luego la nata y la harina, sin batir de más."),
      S("Vierte sobre la base y hornea 55 minutos: los bordes deben estar firmes y el centro aún temblar.", 55, 170),
      S("Apaga el horno y deja la tarta dentro con la puerta entreabierta 1 hora (así no se agrieta). Luego, nevera al menos 6 horas."),
    ],
  }),
  r({
    id: "ensalada-cesar", title: "Ensalada César con pollo", cuisine: "estadounidense", authenticity: "adapted",
    origin: "México (Tijuana) y EE. UU.", note: "La original no lleva pollo ni anchoas, que se añadieron después. La salsa lleva yema cruda.",
    baseServings: 2, prepMin: 20, cookMin: 15, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("lechuga", 1, "unit"), I("pollo", 300, "g"), I("pan", 100, "g"), I("parmesano", 40, "g"), I("huevo", 1, "unit"), I("ajo", 1, "unit"), I("limon", 1, "unit"), I("mostaza", 10, "g"), I("aceite", 90, "ml"), I("sal", 3, "g")],
    steps: [
      S("Corta el pan en dados y dóralo en una sartén con 2 cucharadas de aceite 5 minutos: son los picatostes.", 5),
      S("Sala el pollo y hazlo a la plancha 5 minutos por lado. Córtalo en tiras.", 10),
      S("Para la salsa, mezcla la yema con el ajo rallado, la mostaza y el zumo de limón. Añade el resto del aceite poco a poco batiendo, y la mitad del parmesano rallado."),
      S("Mezcla la lechuga troceada con la salsa y reparte el pollo, los picatostes y el resto del parmesano."),
    ],
  }),
  r({
    id: "sopa-pollo-fideos", title: "Sopa de pollo con fideos", cuisine: "estadounidense", authenticity: "traditional",
    origin: "Estados Unidos", baseServings: 4, prepMin: 15, cookMin: 50, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("pollo", 600, "g"), I("zanahoria", 200, "g"), I("apio", 100, "g"), I("cebolla", 1, "unit"), I("pasta", 120, "g"), I("perejil", 10, "g"), I("sal", 8, "g"), I("pimienta", 1, "g")],
    steps: [
      S("Cuece el pollo con media cebolla, la sal y 2 litros de agua a fuego suave 35 minutos, retirando la espuma.", 35),
      S("Saca el pollo y desmenúzalo sin piel ni huesos.", 5),
      S("Añade al caldo la zanahoria y el apio en rodajas y el resto de la cebolla picada y cocina 8 minutos.", 8),
      S("Añade los fideos y el pollo y cocina según el paquete (unos 5 minutos). Termina con perejil y pimienta.", 5),
    ],
  }),
  // ——— Cuba ———
  r({
    id: "ropa-vieja", title: "Ropa vieja", cuisine: "cubana", authenticity: "traditional",
    origin: "Cuba", note: "Se hace con falda de ternera, que se deshilacha muy bien.",
    baseServings: 4, prepMin: 20, cookMin: 120, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("ternera", 800, "g"), I("tomate-triturado", 400, "g"), I("pimiento", 2, "unit"), I("cebolla", 1, "unit"), I("ajo", 4, "unit"), I("comino", 3, "g"), I("vino-blanco", 100, "ml"), I("arroz", 320, "g"), I("aceite", 40, "ml"), I("sal", 8, "g")],
    steps: [
      S("Cuece la carne en agua con sal a fuego suave 80 minutos, hasta que se deshaga. Deja templar y deshiláchala con dos tenedores.", 80),
      S("Sofríe la cebolla, los pimientos en tiras y el ajo en el aceite 10 minutos.", 10),
      S("Añade el comino, el vino, el tomate y la carne con un poco de su caldo. Cocina 20 minutos a fuego suave.", 20),
      S("Sirve con arroz blanco cocido 15 minutos.", 15),
    ],
  }),
  r({
    id: "moros-y-cristianos", title: "Moros y cristianos", cuisine: "cubana", authenticity: "adapted",
    origin: "Cuba", note: "Se cocina el arroz en el caldo de los frijoles; con frijoles de bote se usa su líquido.",
    baseServings: 4, prepMin: 10, cookMin: 30, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("arroz", 300, "g"), I("frijoles-negros", 400, "g"), I("panceta", 80, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("ajo", 3, "unit"), I("comino", 3, "g"), I("oregano", 1, "g"), I("aceite", 20, "ml"), I("sal", 6, "g")],
    steps: [
      S("Dora la panceta en dados en el aceite 4 minutos. Añade la cebolla, el pimiento y el ajo picados y sofríe 8 minutos.", 12),
      S("Añade el comino, el orégano y el arroz y remueve 1 minuto.", 1),
      S("Agrega los frijoles con su líquido y agua hasta tener 650 ml de líquido en total. Sala.", 1),
      S("Cuando hierva, tapa y cocina a fuego bajo 18 minutos. Deja reposar 5 minutos.", 23),
    ],
  }),
  r({
    id: "picadillo-cubano", title: "Picadillo a la cubana", cuisine: "cubana", authenticity: "adapted",
    origin: "Cuba", note: "La receta tradicional lleva pasas; aquí se omiten.",
    baseServings: 4, prepMin: 15, cookMin: 30, difficulty: "easy", equipment: ["sarten", "olla"],
    ingredients: [I("ternera-picada", 500, "g"), I("patata", 300, "g"), I("tomate-triturado", 200, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("ajo", 2, "unit"), I("aceitunas", 60, "g"), I("comino", 3, "g"), I("vino-blanco", 60, "ml"), I("arroz", 320, "g"), I("aceite", 40, "ml"), I("sal", 6, "g")],
    steps: [
      S("Corta la patata en dados de 1 cm y fríela en la mitad del aceite 8 minutos. Resérvala.", 8),
      S("Sofríe la cebolla, el pimiento y el ajo en el resto del aceite 6 minutos. Añade la carne y el comino y dora 8 minutos.", 14),
      S("Agrega el vino, el tomate y las aceitunas y cocina 8 minutos. Incorpora la patata.", 8),
      S("Sirve con arroz blanco (cocido 15 minutos). En Cuba se acompaña de plátano frito.", 15),
    ],
  }),
  // ——— Colombia y Venezuela ———
  r({
    id: "arepas", title: "Arepas de queso", cuisine: "colombiana", authenticity: "traditional",
    origin: "Colombia y Venezuela", note: "Imprescindible la harina de maíz precocida. Se rellenan de lo que quieras.",
    baseServings: 3, prepMin: 15, cookMin: 20, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("harina-maiz", 250, "g"), I("queso", 100, "g"), I("mantequilla", 20, "g"), I("sal", 4, "g")],
    steps: [
      S("Mezcla la harina con la sal y 330 ml de agua templada. Amasa 2 minutos hasta tener una masa suave que no se agriete; deja reposar 5 minutos.", 7),
      S("Mezcla la mitad del queso rallado con la masa. Forma 6 bolas y aplánalas a 1,5 cm de grosor."),
      S("Cocínalas en una sartén con unas gotas de mantequilla a fuego medio-bajo 8 minutos por cada lado, hasta que tengan costra y suenen huecas al golpearlas.", 16),
      S("Ábrelas por la mitad y rellena con el resto del queso y mantequilla (o carne, frijoles, aguacate…)."),
    ],
  }),
  r({
    id: "ajiaco", title: "Ajiaco santafereño", cuisine: "colombiana", authenticity: "adapted",
    origin: "Colombia (Bogotá)", note: "Lleva tres tipos de patata (incluida la papa criolla) y guascas, una hierba difícil de encontrar fuera.",
    baseServings: 4, prepMin: 20, cookMin: 60, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("pollo", 700, "g"), I("patata", 1000, "g"), I("maiz", 280, "g"), I("cebolleta", 2, "unit"), I("ajo", 2, "unit"), I("cilantro", 15, "g"), I("caldo", 1500, "ml"), I("nata", 150, "ml"), I("aguacate", 1, "unit"), I("sal", 6, "g")],
    steps: [
      S("Cuece el pollo en el caldo con la cebolleta y el ajo 30 minutos. Sácalo y desmenúzalo.", 30),
      S("Añade la mitad de las patatas en rodajas finas (se desharán y espesarán) y la otra mitad en trozos. Cocina 25 minutos.", 25),
      S("Incorpora el maíz y el pollo y cocina 5 minutos. Ajusta de sal.", 5),
      S("Sirve con nata, aguacate y cilantro picado."),
    ],
  }),
  r({
    id: "pabellon-criollo", title: "Pabellón criollo", cuisine: "venezolana", authenticity: "adapted",
    origin: "Venezuela", note: "Plato nacional: carne mechada, caraotas (frijoles negros), arroz y tajadas de plátano maduro.",
    baseServings: 4, prepMin: 20, cookMin: 110, difficulty: "medium", equipment: ["olla", "sarten"],
    ingredients: [I("ternera", 700, "g"), I("frijoles-negros", 400, "g"), I("arroz", 300, "g"), I("platano", 2, "unit"), I("tomate", 300, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("ajo", 3, "unit"), I("comino", 3, "g"), I("aceite", 200, "ml"), I("sal", 8, "g")],
    steps: [
      S("Cuece la carne en agua con sal 75 minutos hasta que esté muy tierna. Mecha (deshilacha) la carne.", 75),
      S("Sofríe la cebolla, el pimiento y el ajo en 3 cucharadas de aceite 8 minutos. Añade el tomate, el comino y la carne con un cazo de caldo y cocina 15 minutos.", 23),
      S("Calienta los frijoles con un poco de sal y cuece el arroz 15 minutos.", 15),
      S("Corta los plátanos en láminas en diagonal y fríelos en el resto del aceite 3 minutos hasta que estén dorados.", 3),
      S("Sirve todo junto en el plato."),
    ],
  }),
  // ——— Perú ———
  r({
    id: "aji-de-gallina", title: "Ají de gallina", cuisine: "peruana", authenticity: "adapted",
    origin: "Perú", note: "Lleva ají amarillo, imprescindible para el color y el sabor; aquí se sustituye por chile y un poco de curry.",
    baseServings: 4, prepMin: 20, cookMin: 45, difficulty: "medium", equipment: ["olla", "sarten", "batidora"],
    ingredients: [I("pollo", 600, "g"), I("pan", 100, "g"), I("leche", 300, "ml"), I("chile", 2, "unit"), I("curry", 4, "g"), I("nueces", 40, "g"), I("parmesano", 40, "g"), I("cebolla", 1, "unit"), I("ajo", 2, "unit"), I("patata", 500, "g"), I("huevo", 2, "unit"), I("arroz", 320, "g"), I("aceite", 40, "ml"), I("sal", 7, "g")],
    steps: [
      S("Cuece el pollo en agua con sal 25 minutos y desmenúzalo. Reserva el caldo. Remoja el pan en la leche.", 25),
      S("Sofríe la cebolla, el ajo y el chile picados en el aceite 8 minutos. Tritura con el pan remojado, las nueces y el curry.", 10),
      S("Calienta la crema 5 minutos, añadiendo caldo hasta que esté espesa. Incorpora el pollo y el queso y cocina 5 minutos.", 10),
      S("Sirve con patata cocida en rodajas, huevo duro, arroz blanco y aceitunas si tienes."),
    ],
  }),
  r({
    id: "papa-huancaina", title: "Papa a la huancaína", cuisine: "peruana", authenticity: "adapted",
    origin: "Perú (Huancayo)", note: "La salsa lleva ají amarillo y queso fresco; aquí, chile, una pizca de curry para el color y queso.",
    baseServings: 4, prepMin: 15, cookMin: 25, difficulty: "easy", equipment: ["olla", "batidora"],
    ingredients: [I("patata", 800, "g"), I("queso", 150, "g"), I("leche", 150, "ml"), I("chile", 2, "unit"), I("curry", 2, "g"), I("galletas", 30, "g"), I("huevo", 2, "unit"), I("lechuga", 1, "unit"), I("aceitunas", 40, "g"), I("aceite", 30, "ml"), I("sal", 5, "g")],
    steps: [
      S("Cuece las patatas con piel 22 minutos y los huevos 10 minutos. Pela y corta en rodajas.", 22),
      S("Tritura el queso con la leche, el chile, el curry, las galletas y el aceite hasta tener una crema espesa y lisa.", 2),
      S("Coloca hojas de lechuga en una fuente, encima las patatas, y cúbrelas con la salsa."),
      S("Decora con el huevo y las aceitunas. Se sirve frío o templado."),
    ],
  }),
  r({
    id: "arroz-chaufa", title: "Arroz chaufa", cuisine: "peruana", authenticity: "traditional",
    origin: "Perú (cocina chifa)", baseServings: 3, prepMin: 15, cookMin: 15, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("arroz", 240, "g"), I("pollo", 300, "g"), I("huevo", 3, "unit"), I("cebolleta", 3, "unit"), I("jengibre", 10, "g"), I("ajo", 2, "unit"), I("soja", 40, "ml"), I("aceite", 40, "ml")],
    steps: [
      S("Usa arroz cocido y frío. Haz una tortilla fina con los huevos, enróllala y córtala en tiras.", 3),
      S("Saltea el pollo en dados en el aceite a fuego muy fuerte 5 minutos.", 5),
      S("Añade el ajo, el jengibre y la parte blanca de la cebolleta 1 minuto. Incorpora el arroz y saltea 4 minutos.", 5),
      S("Añade la soja, el huevo y la parte verde de la cebolleta y saltea 1 minuto más.", 1),
    ],
  }),
  // ——— Argentina y Chile ———
  r({
    id: "locro", title: "Locro", cuisine: "argentina", authenticity: "adapted",
    origin: "Argentina", note: "Guiso patrio del 25 de mayo. Se hace con maíz blanco partido; aquí, maíz dulce.",
    baseServings: 6, prepMin: 20, cookMin: 120, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("maiz", 560, "g"), I("alubias-blancas", 400, "g"), I("calabaza", 600, "g"), I("ternera", 500, "g"), I("chorizo", 200, "g"), I("panceta", 150, "g"), I("cebolla", 1, "unit"), I("pimenton", 8, "g"), I("comino", 3, "g"), I("aceite", 30, "ml"), I("sal", 9, "g")],
    steps: [
      S("En una olla grande, dora la panceta, el chorizo y la ternera en trozos 10 minutos.", 10),
      S("Añade la calabaza en dados y 2 litros de agua con sal. Cocina a fuego suave 80 minutos, removiendo, hasta que la calabaza se deshaga.", 80),
      S("Añade el maíz y las alubias y cocina 20 minutos más.", 20),
      S("Para la salsa (quiquirimichi), sofríe la cebolla picada en el aceite 6 minutos y añade el pimentón y el comino. Sírvela por encima.", 7),
    ],
  }),
  r({
    id: "provoleta", title: "Provoleta", cuisine: "argentina", authenticity: "adapted",
    origin: "Argentina", note: "Se hace con queso provolone a la parrilla; en sartén de hierro también funciona.",
    baseServings: 2, prepMin: 5, cookMin: 10, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("queso", 250, "g"), I("oregano", 2, "g"), I("chile", 1, "unit", true), I("aceite", 15, "ml"), I("pan", 150, "g")],
    steps: [
      S("Corta el queso en una rodaja gruesa de 2 cm. Espolvorea orégano y chile picado por ambos lados."),
      S("Calienta una sartén de hierro a fuego fuerte con unas gotas de aceite. Pon el queso y cocina 3 minutos sin tocarlo, hasta que tenga costra.", 3),
      S("Dale la vuelta con una espátula y cocina 2 minutos más: por dentro debe estar fundido.", 2),
      S("Sirve enseguida con pan y un chorro de aceite."),
    ],
  }),
  r({
    id: "pastel-de-choclo", title: "Pastel de choclo", cuisine: "chilena", authenticity: "adapted",
    origin: "Chile", note: "Se hace con choclo (maíz) fresco molido y albahaca; aquí, maíz de lata.",
    baseServings: 6, prepMin: 30, cookMin: 60, difficulty: "medium", equipment: ["horno", "sarten", "batidora"],
    ingredients: [I("maiz", 840, "g"), I("ternera-picada", 500, "g"), I("cebolla", 2, "unit"), I("huevo", 2, "unit"), I("aceitunas", 60, "g"), I("leche", 150, "ml"), I("mantequilla", 30, "g"), I("albahaca", 10, "g"), I("comino", 3, "g"), I("pimenton", 5, "g"), I("azucar", 15, "g"), I("aceite", 30, "ml"), I("sal", 8, "g")],
    steps: [
      S("Cuece los huevos 10 minutos. Sofríe la cebolla en el aceite 8 minutos, añade la carne, el comino, el pimentón y sal, y cocina 10 minutos (es el pino).", 20),
      S("Tritura el maíz con la leche y la albahaca. Cocina la pasta con la mantequilla y sal a fuego medio 8 minutos, removiendo, hasta que espese.", 8),
      S("Precalienta el horno a 200 °C. Pon el pino en una fuente con los huevos en rodajas y las aceitunas.", 10, 200),
      S("Cubre con la pasta de maíz, espolvorea el azúcar y hornea 30 minutos hasta que la superficie esté dorada.", 30, 200),
    ],
  }),
  // ——— Brasil ———
  r({
    id: "feijoada", title: "Feijoada", cuisine: "brasilena", authenticity: "adapted",
    origin: "Brasil", note: "Versión simplificada con frijoles de bote y costilla, chorizo y panceta en lugar de las partes de cerdo saladas tradicionales.",
    baseServings: 6, prepMin: 20, cookMin: 90, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("frijoles-negros", 1200, "g"), I("costillas-cerdo", 600, "g"), I("chorizo", 200, "g"), I("panceta", 200, "g"), I("cebolla", 1, "unit"), I("ajo", 4, "unit"), I("naranja", 2, "unit"), I("arroz", 450, "g"), I("aceite", 30, "ml"), I("sal", 6, "g")],
    steps: [
      S("Dora las costillas en trozos, la panceta y el chorizo en el aceite 10 minutos.", 10),
      S("Añade la cebolla y el ajo picados y sofríe 5 minutos.", 5),
      S("Incorpora los frijoles con su líquido y 600 ml de agua. Cocina tapado a fuego suave 70 minutos, removiendo de vez en cuando.", 70),
      S("Sirve con arroz blanco y gajos de naranja, como se toma en Brasil.", 15),
    ],
  }),
  r({
    id: "brigadeiros", title: "Brigadeiros", cuisine: "brasilena", authenticity: "traditional",
    origin: "Brasil", note: "Salen unos 20. Imprescindibles en cualquier cumpleaños brasileño.",
    baseServings: 6, prepMin: 20, cookMin: 15, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("leche-condensada", 370, "g"), I("cacao", 25, "g"), I("mantequilla", 20, "g"), I("chocolate", 30, "g", true)],
    steps: [
      S("Pon la leche condensada, el cacao y la mantequilla en un cazo a fuego medio-bajo.", 1),
      S("Remueve sin parar 12 minutos, hasta que la mezcla se despegue del fondo al inclinar el cazo.", 12),
      S("Pásala a un plato untado con mantequilla y deja enfriar del todo (1 hora)."),
      S("Con las manos untadas de mantequilla, forma bolitas y rebózalas en chocolate rallado o fideos de chocolate."),
    ],
  }),
  r({
    id: "bobo-gambas", title: "Bobó de gambas", cuisine: "brasilena", authenticity: "adapted",
    origin: "Brasil (Bahía)", note: "Se hace con mandioca (yuca); aquí, boniato. Sin aceite de dendê.",
    baseServings: 4, prepMin: 20, cookMin: 35, difficulty: "medium", equipment: ["olla", "batidora"],
    ingredients: [I("gambas", 500, "g"), I("boniato", 500, "g"), I("leche-coco", 400, "ml"), I("tomate", 300, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("ajo", 3, "unit"), I("cilantro", 15, "g"), I("lima", 1, "unit"), I("pimenton", 4, "g"), I("arroz", 300, "g"), I("aceite", 30, "ml"), I("sal", 6, "g")],
    steps: [
      S("Cuece el boniato pelado en trozos 15 minutos y tritúralo con la leche de coco hasta tener una crema.", 15),
      S("Sofríe la cebolla, el pimiento y el ajo en el aceite 8 minutos. Añade el tomate picado y el pimentón y cocina 5 minutos.", 13),
      S("Incorpora la crema de boniato y cocina 3 minutos. Añade las gambas peladas, marinadas en lima y sal, y cocina 3 minutos más.", 6),
      S("Termina con cilantro y sirve con arroz blanco.", 15),
    ],
  }),
  // ——— África ———
  r({
    id: "jollof-rice", title: "Arroz jollof", cuisine: "nigeriana", authenticity: "adapted",
    origin: "Nigeria y Ghana", note: "Cada país de África occidental defiende su versión. Esta es de estilo nigeriano, sin pimiento scotch bonnet.",
    baseServings: 4, prepMin: 15, cookMin: 45, difficulty: "medium", equipment: ["olla", "batidora"],
    ingredients: [I("arroz", 350, "g"), I("tomate", 400, "g"), I("tomate-triturado", 150, "g"), I("pimiento", 2, "unit"), I("cebolla", 2, "unit"), I("chile", 2, "unit"), I("curry", 8, "g"), I("caldo", 700, "ml"), I("aceite", 60, "ml"), I("sal", 6, "g")],
    steps: [
      S("Tritura el tomate, los pimientos, una cebolla y los chiles hasta tener una salsa lisa.", 2),
      S("Sofríe la otra cebolla picada en el aceite 5 minutos. Añade el tomate triturado y el curry y fríe 3 minutos.", 8),
      S("Añade la salsa triturada y cocina 15 minutos hasta que espese y el aceite salga a la superficie.", 15),
      S("Incorpora el arroz lavado y el caldo con la sal. Tapa y cocina a fuego bajo 22 minutos sin remover. Un poco de fondo tostado es parte del plato.", 22),
    ],
  }),
  r({
    id: "misir-wot", title: "Misir wot (lentejas etíopes)", cuisine: "etiope", authenticity: "adapted",
    origin: "Etiopía", note: "Lleva berbere (mezcla de especias picante) y niter kibbeh (mantequilla especiada); aquí se imitan con pimentón, chile y especias.",
    baseServings: 4, prepMin: 10, cookMin: 40, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("lentejas", 300, "g"), I("cebolla", 2, "unit"), I("ajo", 4, "unit"), I("jengibre", 15, "g"), I("pimenton", 10, "g"), I("chile", 2, "unit"), I("comino", 3, "g"), I("canela", 1, "g"), I("tomate-triturado", 150, "g"), I("mantequilla", 40, "g"), I("sal", 6, "g")],
    steps: [
      S("Pica la cebolla muy fina y cocínala en seco a fuego medio 8 minutos, removiendo, hasta que pierda el agua. Añade la mantequilla.", 8),
      S("Agrega el ajo, el jengibre, el chile y las especias y cocina 2 minutos. Añade el tomate 3 minutos.", 5),
      S("Incorpora las lentejas lavadas y 900 ml de agua. Cocina 25 minutos removiendo hasta que estén deshechas y espesas.", 25),
      S("Ajusta de sal. En Etiopía se come con injera (pan esponjoso de teff); con pan plano o arroz también va bien."),
    ],
  }),
  r({
    id: "pollo-yassa", title: "Pollo yassa", cuisine: "senegalesa", authenticity: "traditional",
    origin: "Senegal", note: "El secreto es mucha cebolla y una marinada larga con limón.",
    baseServings: 4, prepMin: 135, cookMin: 50, difficulty: "easy", equipment: ["olla", "sarten"],
    ingredients: [I("pollo", 1000, "g"), I("cebolla", 4, "unit"), I("limon", 3, "unit"), I("mostaza", 30, "g"), I("ajo", 3, "unit"), I("chile", 1, "unit"), I("aceitunas", 50, "g", true), I("arroz", 320, "g"), I("aceite", 50, "ml"), I("sal", 8, "g")],
    steps: [
      S("Mezcla el zumo de los limones, la mostaza, el ajo rallado, el chile, la sal y el aceite. Marina el pollo y las cebollas en juliana al menos 2 horas.", 120),
      S("Saca el pollo y dóralo en una sartén 10 minutos.", 10),
      S("En una olla, cocina las cebollas con la marinada a fuego medio 20 minutos, hasta que estén blandas y doradas.", 20),
      S("Añade el pollo y 150 ml de agua y cocina tapado 15 minutos. Añade las aceitunas los últimos 2 minutos y sirve con arroz blanco.", 15),
    ],
  }),
  r({
    id: "bobotie", title: "Bobotie", cuisine: "sudafricana", authenticity: "adapted",
    origin: "Sudáfrica (cocina malaya del Cabo)", note: "Lleva chutney de fruta y pasas; aquí se usa manzana para el punto dulce.",
    baseServings: 6, prepMin: 20, cookMin: 50, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("ternera-picada", 700, "g"), I("cebolla", 2, "unit"), I("pan", 60, "g"), I("leche", 300, "ml"), I("huevo", 2, "unit"), I("curry", 12, "g"), I("manzana", 1, "unit"), I("limon", 1, "unit"), I("almendras", 30, "g"), I("aceite", 30, "ml"), I("sal", 8, "g")],
    steps: [
      S("Remoja el pan en la mitad de la leche. Sofríe la cebolla en el aceite 8 minutos y añade el curry 1 minuto.", 9),
      S("Añade la carne y dórala 8 minutos. Agrega la manzana rallada, el zumo de limón, el pan escurrido y la sal.", 8),
      S("Precalienta el horno a 180 °C. Pasa la carne a una fuente y alísala.", 10, 180),
      S("Bate los huevos con el resto de la leche, viértelo por encima, reparte las almendras y hornea 30 minutos hasta que la capa de huevo cuaje y se dore.", 30, 180),
    ],
  }),
  // ——— Oriente Medio y Magreb ———
  r({
    id: "shawarma-pollo", title: "Shawarma de pollo", cuisine: "oriente-medio", authenticity: "adapted",
    origin: "Oriente Medio", note: "Sin asador vertical: el pollo marinado se hace en sartén o al horno.",
    baseServings: 4, prepMin: 40, cookMin: 15, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("pollo", 600, "g"), I("yogur", 1, "unit"), I("ajo", 3, "unit"), I("comino", 4, "g"), I("pimenton", 5, "g"), I("curry", 4, "g"), I("limon", 1, "unit"), I("pan-pita", 4, "unit"), I("tomate", 200, "g"), I("cebolla", 0.5, "unit"), I("tahini", 40, "g"), I("aceite", 30, "ml"), I("sal", 6, "g")],
    steps: [
      S("Corta el pollo (mejor muslo) en tiras y marínalo con el yogur, 2 ajos, las especias, la mitad del zumo de limón y la sal 30 minutos.", 30),
      S("Cocínalo en una sartén muy caliente con el aceite 10 minutos, dejándolo tostarse por zonas.", 10),
      S("Mezcla el tahini con el resto del limón, el otro ajo y agua hasta una salsa fluida."),
      S("Calienta las pitas y rellénalas con el pollo, tomate, cebolla en aros y la salsa.", 2),
    ],
  }),
  r({
    id: "tabule", title: "Tabulé", cuisine: "oriente-medio", authenticity: "traditional",
    origin: "Líbano", note: "El tabulé libanés es sobre todo perejil; el bulgur es el acompañante, no al revés.",
    baseServings: 4, prepMin: 25, cookMin: 0, difficulty: "easy",
    ingredients: [I("bulgur", 60, "g"), I("perejil", 80, "g"), I("menta", 15, "g"), I("tomate", 300, "g"), I("cebolleta", 2, "unit"), I("limon", 2, "unit"), I("aceite", 60, "ml"), I("sal", 4, "g")],
    steps: [
      S("Remoja el bulgur en agua fría 15 minutos y escúrrelo apretando bien.", 15),
      S("Pica muy fino (a cuchillo) el perejil y la menta. Corta el tomate en dados pequeños y la cebolleta fina."),
      S("Mezcla todo con el zumo de limón, el aceite y la sal. Sirve enseguida con hojas de lechuga para comerlo."),
    ],
  }),
  r({
    id: "baba-ganoush", title: "Baba ganoush", cuisine: "oriente-medio", authenticity: "traditional",
    origin: "Levante (Líbano, Siria)", baseServings: 4, prepMin: 10, cookMin: 40, difficulty: "easy", equipment: ["horno"],
    ingredients: [I("berenjena", 700, "g"), I("tahini", 50, "g"), I("limon", 1, "unit"), I("ajo", 1, "unit"), I("aceite", 30, "ml"), I("perejil", 5, "g", true), I("sal", 4, "g")],
    steps: [
      S("Asa las berenjenas enteras y pinchadas en el horno a 220 °C 40 minutos (o directamente sobre el fuego del gas, girándolas) hasta que la piel se queme y estén muy blandas.", 40, 220),
      S("Ábrelas, saca la pulpa con una cuchara y déjala escurrir 10 minutos en un colador."),
      S("Aplástala con un tenedor y mézclala con el tahini, el zumo de limón, el ajo rallado y la sal."),
      S("Sirve con un chorro de aceite y perejil, con pan de pita."),
    ],
  }),
  r({
    id: "mujaddara", title: "Mujaddara (arroz con lentejas y cebolla)", cuisine: "oriente-medio", authenticity: "traditional",
    origin: "Levante", note: "Plato humilde y muy sabroso: la cebolla bien frita es lo que lo hace especial.",
    baseServings: 4, prepMin: 10, cookMin: 50, difficulty: "easy", equipment: ["olla", "sarten"],
    ingredients: [I("lentejas", 200, "g"), I("arroz", 200, "g"), I("cebolla", 3, "unit"), I("comino", 4, "g"), I("aceite", 80, "ml"), I("yogur", 2, "unit", true), I("sal", 7, "g")],
    steps: [
      S("Cuece las lentejas en agua 15 minutos (deben quedar firmes). Escúrrelas reservando el agua.", 15),
      S("Fríe las cebollas en juliana en el aceite a fuego medio 25 minutos, removiendo, hasta que estén muy doradas. Reserva la mitad.", 25),
      S("Añade a la olla el comino, el arroz, las lentejas y 450 ml del agua de cocción con la sal. Tapa y cocina a fuego bajo 15 minutos.", 15),
      S("Sirve con la cebolla frita reservada por encima y yogur.", 1),
    ],
  }),
  r({
    id: "fattoush", title: "Ensalada fattoush", cuisine: "oriente-medio", authenticity: "adapted",
    origin: "Líbano", note: "Lleva zumaque, una especia ácida y rojiza; aquí se compensa con más limón.",
    baseServings: 4, prepMin: 20, cookMin: 10, difficulty: "easy", equipment: ["horno"],
    ingredients: [I("pan-pita", 2, "unit"), I("lechuga", 1, "unit"), I("tomate", 300, "g"), I("pepino", 200, "g"), I("cebolleta", 2, "unit"), I("perejil", 20, "g"), I("menta", 10, "g"), I("limon", 2, "unit"), I("aceite", 60, "ml"), I("sal", 4, "g")],
    steps: [
      S("Corta el pan de pita en trozos y tuéstalo en el horno a 200 °C 8 minutos hasta que esté crujiente.", 8, 200),
      S("Corta la lechuga, el tomate, el pepino y la cebolleta en trozos y pica las hierbas."),
      S("Aliña con el zumo de limón, el aceite y la sal. Añade el pan justo antes de servir para que siga crujiente."),
    ],
  }),
  r({
    id: "cuscus-verduras", title: "Cuscús de verduras", cuisine: "marroqui", authenticity: "adapted",
    origin: "Marruecos", note: "En Marruecos el cuscús se cocina al vapor sobre el guiso en una cuscusera.",
    baseServings: 4, prepMin: 20, cookMin: 40, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("cuscus", 300, "g"), I("zanahoria", 200, "g"), I("calabacin", 300, "g"), I("calabaza", 300, "g"), I("garbanzos-cocidos", 400, "g"), I("cebolla", 1, "unit"), I("tomate", 200, "g"), I("comino", 3, "g"), I("canela", 2, "g"), I("jengibre", 10, "g"), I("caldo", 800, "ml"), I("aceite", 40, "ml"), I("mantequilla", 20, "g"), I("sal", 7, "g")],
    steps: [
      S("Sofríe la cebolla en el aceite 6 minutos. Añade el jengibre, el comino y la canela 1 minuto, y el tomate picado 3 minutos.", 10),
      S("Añade la zanahoria, la calabaza y el caldo y cocina 15 minutos. Agrega el calabacín y los garbanzos y cocina 10 minutos más.", 25),
      S("Pon el cuscús en un bol con la mantequilla y vierte por encima la misma cantidad de caldo hirviendo del guiso. Tapa 5 minutos y suéltalo con un tenedor.", 5),
      S("Sirve el cuscús con las verduras y el caldo por encima."),
    ],
  }),
  r({
    id: "zaalouk", title: "Zaalouk (ensalada marroquí de berenjena)", cuisine: "marroqui", authenticity: "traditional",
    origin: "Marruecos", baseServings: 4, prepMin: 10, cookMin: 35, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("berenjena", 600, "g"), I("tomate", 400, "g"), I("ajo", 3, "unit"), I("comino", 3, "g"), I("pimenton", 4, "g"), I("cilantro", 15, "g"), I("limon", 0.5, "unit"), I("aceite", 60, "ml"), I("sal", 5, "g")],
    steps: [
      S("Pela la berenjena a tiras y córtala en dados. Pela y pica el tomate."),
      S("Pon todo en una sartén con el ajo picado, las especias, la sal, el aceite y 100 ml de agua. Tapa y cocina 20 minutos.", 20),
      S("Destapa y aplasta con un tenedor. Cocina 10 minutos más, removiendo, hasta que se evapore el líquido.", 10),
      S("Añade el cilantro y el limón. Se sirve templado o frío, con pan."),
    ],
  }),
  // ——— Clásicos caseros ———
  r({
    id: "tarta-de-queso-vasca", title: "Tarta de queso al estilo de La Viña", cuisine: "espanola", authenticity: "traditional",
    origin: "España (San Sebastián)", note: "Quemada por fuera y cremosa por dentro. Se hornea a temperatura muy alta.",
    baseServings: 8, prepMin: 10, cookMin: 40, difficulty: "easy", equipment: ["horno"],
    ingredients: [I("queso-crema", 600, "g"), I("azucar", 200, "g"), I("huevo", 4, "unit"), I("nata", 300, "ml"), I("harina", 15, "g")],
    steps: [
      S("Precalienta el horno a 220 °C. Forra un molde de 22 cm con papel de horno arrugado, que sobresalga por los bordes.", 10, 220),
      S("Bate el queso con el azúcar. Añade los huevos de uno en uno, luego la nata y por último la harina tamizada. No hace falta montar nada."),
      S("Vierte en el molde y hornea 35 minutos: la superficie debe quedar muy tostada y el centro temblar como un flan.", 35, 220),
      S("Deja enfriar a temperatura ambiente. Se puede tomar así o tras unas horas en la nevera."),
    ],
  }),
  r({
    id: "natillas", title: "Natillas caseras", cuisine: "espanola", authenticity: "traditional",
    origin: "España", baseServings: 6, prepMin: 10, cookMin: 15, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("leche", 750, "ml"), I("huevo", 5, "unit"), I("azucar", 120, "g"), I("harina", 20, "g"), I("canela", 5, "g"), I("limon", 1, "unit"), I("galletas", 30, "g", true)],
    steps: [
      S("Calienta 600 ml de leche con la canela en rama y la piel de limón hasta que hierva. Retira del fuego.", 5),
      S("Bate las yemas con el azúcar y la harina disuelta en el resto de la leche fría."),
      S("Cuela la leche caliente sobre las yemas y vuelve al cazo a fuego bajo. Remueve sin parar 7 minutos, hasta que espese sin hervir.", 7),
      S("Reparte en cuencos, pon una galleta encima y espolvorea canela. Refrigera al menos 2 horas."),
    ],
  }),
  r({
    id: "crema-de-calabaza", title: "Crema de calabaza", cuisine: "espanola", authenticity: "traditional",
    origin: "España", baseServings: 4, prepMin: 15, cookMin: 30, difficulty: "easy", equipment: ["olla", "batidora"],
    ingredients: [I("calabaza", 800, "g"), I("patata", 200, "g"), I("cebolla", 1, "unit"), I("zanahoria", 100, "g"), I("caldo", 800, "ml"), I("nata", 100, "ml", true), I("aceite", 30, "ml"), I("sal", 5, "g")],
    steps: [
      S("Pocha la cebolla en el aceite 6 minutos.", 6),
      S("Añade la calabaza, la patata y la zanahoria en trozos y rehoga 3 minutos.", 3),
      S("Cubre con el caldo, sala y cocina 20 minutos hasta que todo esté muy tierno.", 20),
      S("Tritura hasta que quede muy fina, añade la nata y sirve con un hilo de aceite o pipas tostadas.", 2),
    ],
  }),
  r({
    id: "arroz-a-la-cubana", title: "Arroz a la cubana", cuisine: "espanola", authenticity: "traditional",
    origin: "España", note: "A pesar del nombre, es un plato muy español: arroz blanco, tomate frito, huevo frito y plátano.",
    baseServings: 2, prepMin: 5, cookMin: 25, difficulty: "easy", equipment: ["olla", "sarten"],
    ingredients: [I("arroz", 160, "g"), I("tomate-triturado", 200, "g"), I("huevo", 2, "unit"), I("platano", 2, "unit"), I("ajo", 1, "unit"), I("aceite", 60, "ml"), I("azucar", 3, "g"), I("sal", 5, "g")],
    steps: [
      S("Cuece el arroz con el ajo en agua con sal 15 minutos y escúrrelo.", 15),
      S("Fríe el tomate con una cucharada de aceite, el azúcar y una pizca de sal 8 minutos hasta que espese.", 8),
      S("Fríe los plátanos partidos a lo largo 2 minutos por lado y los huevos con la yema líquida.", 6),
      S("Sirve el arroz en forma de flan, con el tomate, el huevo y el plátano."),
    ],
  }),
];
