import type { Recipe } from "@comocomo/schemas";
import { I, r, S } from "./helpers";

/** Lote 4A: España (más regiones), Asturias y Portugal. Recetas escritas para COMOCOMO. */
export const recipesEspana2: Recipe[] = [
  r({
    id: "cocido-madrileno", title: "Cocido madrileño", cuisine: "espanola", authenticity: "adapted",
    origin: "España (Madrid)", note: "Se sirve en tres vuelcos: primero la sopa con fideos, luego garbanzos y verduras, y al final las carnes. Versión sin repollo ni hueso de tuétano.",
    baseServings: 6, prepMin: 20, cookMin: 190, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("garbanzos", 500, "g"), I("ternera", 400, "g"), I("pollo", 500, "g"), I("chorizo", 200, "g"), I("morcilla", 200, "g"), I("panceta", 150, "g"), I("patata", 600, "g"), I("zanahoria", 250, "g"), I("pasta", 120, "g"), I("sal", 10, "g")],
    steps: [
      S("La víspera, pon los garbanzos en remojo en agua templada con sal durante 12 horas."),
      S("Pon la ternera, el pollo y la panceta en una olla grande con 4 litros de agua fría. Cuando hierva, retira la espuma durante 10 minutos.", 10),
      S("Añade los garbanzos escurridos dentro de una malla (así no se mezclan) y cocina a fuego muy suave, apenas un hervor, 2 horas y media.", 150),
      S("Añade las patatas y zanahorias peladas enteras. Cuece el chorizo y la morcilla aparte en un cazo con agua 20 minutos para que no tiñan el caldo.", 25),
      S("Cuela parte del caldo y cuece en él la pasta fina 5 minutos: es la sopa. Sirve primero la sopa, después los garbanzos con las verduras y por último las carnes.", 5),
    ],
  }),
  r({
    id: "pulpo-a-la-gallega", title: "Pulpo a la gallega", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Galicia)", note: "Con pulpo ya cocido del súper se tarda minutos. En Galicia se sirve en plato de madera.",
    baseServings: 4, prepMin: 10, cookMin: 25, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("pulpo", 500, "g"), I("patata", 600, "g"), I("pimenton", 6, "g"), I("aceite", 50, "ml"), I("sal", 5, "g")],
    steps: [
      S("Cuece las patatas con piel en agua con sal 20 minutos, hasta que un cuchillo entre sin resistencia. Pélalas y córtalas en rodajas de 1 cm.", 20),
      S("Calienta el pulpo 3 minutos en agua caliente (sin hervir fuerte) y córtalo en rodajas de 1 cm con unas tijeras.", 3),
      S("Coloca las patatas en la base del plato y el pulpo encima."),
      S("Espolvorea sal gruesa y pimentón (mitad dulce, mitad picante si lo tienes) y riega con un buen chorro de aceite. Sirve templado."),
    ],
  }),
  r({
    id: "croquetas-jamon", title: "Croquetas de jamón", cuisine: "espanola", authenticity: "traditional",
    origin: "España", note: "Salen unas 30. La masa debe reposar varias horas en la nevera para poder darles forma.",
    baseServings: 6, prepMin: 40, cookMin: 30, difficulty: "hard", equipment: ["sarten"],
    ingredients: [I("jamon", 120, "g"), I("leche", 750, "ml"), I("harina", 90, "g"), I("mantequilla", 60, "g"), I("cebolla", 0.5, "unit"), I("huevo", 2, "unit"), I("pan-rallado", 150, "g"), I("aceite", 500, "ml"), I("sal", 3, "g")],
    steps: [
      S("Pica muy fino la cebolla y el jamón. Pocha la cebolla en la mantequilla a fuego medio-bajo 6 minutos.", 6),
      S("Añade la harina y tuéstala 2 minutos sin dejar de remover. Agrega el jamón.", 2),
      S("Vierte la leche templada poco a poco, removiendo con varillas, y cocina 15 minutos a fuego suave hasta que la masa se despegue de las paredes. Prueba antes de salar: el jamón ya es salado.", 15),
      S("Extiende la masa en una fuente, cubre con film en contacto y deja enfriar en la nevera al menos 4 horas (mejor de un día para otro)."),
      S("Forma las croquetas, pásalas por huevo batido y pan rallado, y fríelas en aceite a 180 °C en tandas pequeñas, 2 minutos, hasta que estén doradas.", 6, 180),
    ],
  }),
  r({
    id: "salmorejo", title: "Salmorejo cordobés", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Córdoba)", baseServings: 4, prepMin: 15, cookMin: 10, difficulty: "easy", equipment: ["batidora", "olla"],
    ingredients: [I("tomate", 1000, "g"), I("pan", 200, "g"), I("ajo", 1, "unit"), I("aceite", 120, "ml"), I("sal", 6, "g"), I("huevo", 2, "unit"), I("jamon", 50, "g")],
    steps: [
      S("Cuece los huevos 10 minutos, enfríalos y pícalos.", 10),
      S("Tritura los tomates con el ajo y la sal 2 minutos. Añade el pan troceado y deja que se empape 5 minutos.", 7),
      S("Vuelve a triturar añadiendo el aceite en un hilo hasta que quede una crema espesa y anaranjada."),
      S("Enfría en la nevera al menos 1 hora. Sirve con el huevo, el jamón picado y un chorrito de aceite."),
    ],
  }),
  r({
    id: "ensaladilla-rusa", title: "Ensaladilla rusa", cuisine: "espanola", authenticity: "traditional",
    origin: "España", note: "La mayonesa casera marca la diferencia. Mantenla siempre en frío.",
    baseServings: 6, prepMin: 25, cookMin: 25, difficulty: "easy", equipment: ["olla", "batidora"],
    ingredients: [I("patata", 700, "g"), I("zanahoria", 150, "g"), I("guisantes", 100, "g"), I("huevo", 4, "unit"), I("atun-lata", 160, "g"), I("aceitunas", 50, "g"), I("aceite", 200, "ml"), I("limon", 0.5, "unit"), I("sal", 6, "g")],
    steps: [
      S("Cuece las patatas y las zanahorias peladas en agua con sal 20 minutos. Añade los guisantes los últimos 3 minutos. Cuece 3 huevos 10 minutos en otro cazo.", 20),
      S("Escurre y deja enfriar. Corta patatas y zanahorias en dados pequeños y pica los huevos."),
      S("Para la mayonesa, pon el huevo crudo restante, el zumo de limón y una pizca de sal en el vaso de la batidora. Bate sin mover la batidora mientras añades el aceite en hilo, hasta que emulsione."),
      S("Mezcla las verduras con el atún escurrido, el huevo picado y la mayonesa. Decora con aceitunas y enfría al menos 1 hora."),
    ],
  }),
  r({
    id: "bacalao-pil-pil", title: "Bacalao al pil-pil", cuisine: "espanola", authenticity: "traditional",
    origin: "España (País Vasco)", note: "El pil-pil es la salsa que se forma al emulsionar la gelatina del bacalao con el aceite moviendo la cazuela. Requiere paciencia.",
    baseServings: 4, prepMin: 10, cookMin: 25, difficulty: "hard", equipment: ["sarten"],
    ingredients: [I("bacalao", 600, "g"), I("ajo", 6, "unit"), I("chile", 1, "unit"), I("aceite", 250, "ml"), I("perejil", 5, "g", true)],
    steps: [
      S("Seca muy bien los lomos de bacalao desalado. Lamina los ajos y corta el chile en aros."),
      S("En una cazuela de barro o sartén, calienta el aceite a fuego bajo con los ajos 4 minutos, hasta que estén dorados. Retira ajos y chile y deja templar el aceite 5 minutos.", 9),
      S("Pon los lomos con la piel hacia arriba en el aceite templado, a fuego muy bajo, 5 minutos. Dales la vuelta y cocina 5 minutos más: deben soltar gelatina.", 10),
      S("Retira el bacalao. Mueve la cazuela en círculos (o bate con un colador) 5 minutos hasta que el aceite se vuelva una salsa espesa y blanquecina.", 5),
      S("Devuelve el bacalao a la salsa, añade los ajos y el chile, espolvorea perejil picado si quieres y sirve en la misma cazuela."),
    ],
  }),
  r({
    id: "merluza-salsa-verde", title: "Merluza en salsa verde con almejas", cuisine: "espanola", authenticity: "traditional",
    origin: "España (País Vasco)", baseServings: 4, prepMin: 10, cookMin: 20, difficulty: "medium", equipment: ["sarten"],
    ingredients: [I("merluza", 600, "g"), I("almejas", 250, "g"), I("ajo", 3, "unit"), I("perejil", 20, "g"), I("harina", 10, "g"), I("vino-blanco", 100, "ml"), I("caldo", 200, "ml"), I("aceite", 50, "ml"), I("sal", 5, "g")],
    steps: [
      S("Pon las almejas en agua con sal 30 minutos para que suelten la arena. Sala la merluza en rodajas o lomos."),
      S("En una cazuela ancha, dora el ajo picado en el aceite 1 minuto a fuego medio. Añade la harina y remueve 1 minuto.", 2),
      S("Vierte el vino y el caldo poco a poco, moviendo la cazuela. Cocina 3 minutos hasta que espese ligeramente.", 3),
      S("Añade la merluza y las almejas, tapa y cocina 6 minutos moviendo la cazuela de vez en cuando. Retira las almejas que no se abran.", 6),
      S("Espolvorea abundante perejil picado y sirve enseguida."),
    ],
  }),
  r({
    id: "fideua", title: "Fideuà de marisco", cuisine: "espanola", authenticity: "adapted",
    origin: "España (Gandía, Valencia)", note: "Se usan fideos finos o pasta corta. Tradicionalmente se sirve con alioli.",
    baseServings: 4, prepMin: 15, cookMin: 35, difficulty: "medium", equipment: ["sarten"],
    ingredients: [I("pasta", 400, "g"), I("gambas", 300, "g"), I("calamares", 300, "g"), I("tomate", 150, "g"), I("ajo", 2, "unit"), I("pimenton", 4, "g"), I("caldo", 1000, "ml"), I("aceite", 60, "ml"), I("sal", 6, "g")],
    steps: [
      S("En una paellera con el aceite, dora las gambas 1 minuto por lado y resérvalas. Dora los calamares en anillas 4 minutos.", 6),
      S("Añade los fideos y tuéstalos 3 minutos removiendo, hasta que se doren un poco.", 3),
      S("Añade el ajo picado y el tomate rallado, cocina 3 minutos. Agrega el pimentón y enseguida el caldo caliente con la sal.", 3),
      S("Cocina a fuego medio-fuerte 12 minutos sin remover, hasta que se consuma el caldo. Coloca las gambas encima los últimos 3 minutos.", 12),
      S("Si quieres que los fideos se ricen hacia arriba, mete la paellera 3 minutos bajo el gratinador. Deja reposar 5 minutos.", 5),
    ],
  }),
  r({
    id: "arroz-al-horno", title: "Arroz al horno", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Valencia)", note: "Se hace en cazuela de barro. Es un plato de aprovechamiento del cocido.",
    baseServings: 4, prepMin: 15, cookMin: 60, difficulty: "medium", equipment: ["horno", "sarten"],
    ingredients: [I("arroz", 300, "g"), I("costillas-cerdo", 400, "g"), I("morcilla", 150, "g"), I("garbanzos-cocidos", 200, "g"), I("patata", 200, "g"), I("tomate", 150, "g"), I("ajo", 10, "unit"), I("caldo", 750, "ml"), I("pimenton", 3, "g"), I("aceite", 50, "ml"), I("sal", 6, "g")],
    steps: [
      S("Precalienta el horno a 220 °C. Corta las costillas en trozos, la patata en rodajas y el tomate en mitades.", 10, 220),
      S("En una sartén con el aceite, dora las costillas 8 minutos, luego la patata 4 minutos y el tomate 2. Dora también la cabeza de ajos entera, cortada por la mitad.", 14),
      S("Añade el arroz y el pimentón a la sartén y remueve 1 minuto. Pásalo todo a una cazuela de barro con los garbanzos, la morcilla en rodajas y los ajos en el centro.", 1),
      S("Vierte el caldo hirviendo con la sal y mete al horno 20 minutos, sin remover, hasta que el arroz esté seco y suelto.", 20, 220),
      S("Deja reposar 5 minutos fuera del horno antes de servir.", 5),
    ],
  }),
  r({
    id: "migas", title: "Migas extremeñas", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Extremadura)", note: "Plato de pastores. El pan duro se humedece la víspera.",
    baseServings: 4, prepMin: 15, cookMin: 30, difficulty: "medium", equipment: ["sarten"],
    ingredients: [I("pan", 400, "g"), I("panceta", 150, "g"), I("chorizo", 150, "g"), I("ajo", 6, "unit"), I("pimiento", 1, "unit"), I("pimenton", 3, "g"), I("aceite", 100, "ml"), I("sal", 3, "g")],
    steps: [
      S("La víspera, corta el pan duro en daditos pequeños, rocíalo con agua con sal (sin empaparlo) y tápalo con un paño húmedo."),
      S("En una sartén grande, fríe los ajos con piel en el aceite 3 minutos y retíralos. Fríe la panceta y el chorizo en trozos 5 minutos y retíralos. Fríe el pimiento en tiras 5 minutos.", 13),
      S("Añade el pan al aceite con el pimentón y remueve a fuego medio durante 15 minutos, cortando con la espumadera, hasta que las migas estén sueltas y doradas.", 15),
      S("Incorpora la carne, el pimiento y los ajos y mezcla 2 minutos. Sirve caliente (en Extremadura, con uvas o un huevo frito).", 2),
    ],
  }),
  r({
    id: "escalivada", title: "Escalivada", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Cataluña)", baseServings: 4, prepMin: 10, cookMin: 60, difficulty: "easy", equipment: ["horno"],
    ingredients: [I("berenjena", 500, "g"), I("pimiento", 3, "unit"), I("cebolla", 2, "unit"), I("aceite", 60, "ml"), I("sal", 4, "g"), I("ajo", 1, "unit", true)],
    steps: [
      S("Precalienta el horno a 200 °C. Lava las verduras y pínchalas con un tenedor. Ponlas enteras en una bandeja con un chorro de aceite.", 10, 200),
      S("Hornea 50 minutos dándoles la vuelta a mitad. Los pimientos y las berenjenas están cuando la piel se arruga y se hunden al tocarlos.", 50, 200),
      S("Mételas en un bol tapado 10 minutos: así se pelan fácilmente.", 10),
      S("Pela las verduras, córtalas en tiras con las manos y aliña con aceite, sal y ajo picado si te gusta. Se sirve templada o fría."),
    ],
  }),
  r({
    id: "pan-con-tomate", title: "Pan con tomate y jamón", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Cataluña)", baseServings: 4, prepMin: 10, cookMin: 5, difficulty: "easy",
    ingredients: [I("pan", 300, "g"), I("tomate", 400, "g"), I("aceite", 40, "ml"), I("sal", 3, "g"), I("ajo", 2, "unit", true), I("jamon", 100, "g", true)],
    steps: [
      S("Corta el pan en rebanadas y tuéstalo 2-3 minutos por cada lado hasta que esté crujiente por fuera.", 5),
      S("Si te gusta, frota cada rebanada con medio diente de ajo."),
      S("Parte los tomates maduros por la mitad y frótalos sobre el pan hasta dejar solo la piel (o rállalos y extiende la pulpa)."),
      S("Sala, riega con aceite y sirve solo o con una loncha de jamón."),
    ],
  }),
  r({
    id: "crema-catalana", title: "Crema catalana", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Cataluña)", note: "Tradicional del 19 de marzo, San José. El azúcar de encima se quema con una pala de hierro o un soplete.",
    baseServings: 6, prepMin: 15, cookMin: 20, difficulty: "medium", equipment: ["olla"],
    ingredients: [I("leche", 750, "ml"), I("huevo", 6, "unit"), I("azucar", 150, "g"), I("harina", 25, "g"), I("canela", 3, "g"), I("limon", 1, "unit")],
    steps: [
      S("Calienta 600 ml de leche con la canela y la piel del limón hasta que hierva. Apaga y deja infusionar 10 minutos.", 12),
      S("Bate las 6 yemas con 100 g de azúcar y la harina disuelta en el resto de la leche fría."),
      S("Cuela la leche caliente sobre las yemas, removiendo. Vuelve al cazo a fuego bajo y remueve sin parar 6 minutos, hasta que espese y cubra la cuchara. No debe hervir.", 6),
      S("Reparte en cazuelitas, deja enfriar y refrigera al menos 3 horas."),
      S("Justo antes de servir, cubre con el resto del azúcar y quémalo con un soplete hasta que forme una capa de caramelo crujiente."),
    ],
  }),
  r({
    id: "torrijas", title: "Torrijas", cuisine: "espanola", authenticity: "traditional",
    origin: "España", note: "Dulce típico de Semana Santa. Mejor con pan del día anterior.",
    baseServings: 6, prepMin: 15, cookMin: 25, difficulty: "easy", equipment: ["sarten", "olla"],
    ingredients: [I("pan", 300, "g"), I("leche", 500, "ml"), I("huevo", 3, "unit"), I("azucar", 100, "g"), I("canela", 5, "g"), I("limon", 1, "unit"), I("aceite", 400, "ml")],
    steps: [
      S("Calienta la leche con 40 g de azúcar, la canela en rama y la piel de limón 5 minutos. Deja templar.", 5),
      S("Corta el pan en rebanadas de 2 cm. Empápalas en la leche 1 minuto por cada lado, sin que se rompan."),
      S("Pásalas por huevo batido y fríelas en el aceite a 170 °C 2 minutos por cada lado, hasta que estén doradas.", 12, 170),
      S("Escúrrelas sobre papel y rebózalas en el resto del azúcar mezclado con canela molida. Están mejor al día siguiente."),
    ],
  }),
  r({
    id: "porrusalda", title: "Porrusalda", cuisine: "espanola", authenticity: "traditional",
    origin: "España (País Vasco)", baseServings: 4, prepMin: 15, cookMin: 35, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("puerro", 4, "unit"), I("patata", 500, "g"), I("zanahoria", 150, "g"), I("ajo", 2, "unit"), I("caldo", 1000, "ml"), I("aceite", 40, "ml"), I("sal", 6, "g"), I("bacalao", 200, "g", true)],
    steps: [
      S("Limpia los puerros y córtalos en rodajas de 2 cm (solo la parte blanca y verde clara). Pela la patata y cáscala en trozos irregulares."),
      S("Pocha el puerro y el ajo en el aceite a fuego medio 8 minutos, sin que se doren.", 8),
      S("Añade la patata y la zanahoria en rodajas y rehoga 2 minutos.", 2),
      S("Cubre con el caldo, sala y cocina a fuego suave 25 minutos, hasta que la patata esté tierna. Si añades bacalao, ponlo desmigado los últimos 5 minutos.", 25),
    ],
  }),
  r({
    id: "ajoblanco", title: "Ajoblanco malagueño", cuisine: "espanola", authenticity: "adapted",
    origin: "España (Málaga)", note: "Tradicionalmente se sirve con uvas moscatel; aquí, con dados de manzana.",
    baseServings: 4, prepMin: 15, cookMin: 0, difficulty: "easy", equipment: ["batidora"],
    ingredients: [I("almendras", 150, "g"), I("pan", 100, "g"), I("ajo", 1, "unit"), I("aceite", 100, "ml"), I("vinagre", 30, "ml"), I("sal", 5, "g"), I("manzana", 1, "unit", true)],
    steps: [
      S("Remoja el pan en agua fría. Si las almendras tienen piel, escáldalas 1 minuto en agua hirviendo y pélalas."),
      S("Tritura las almendras con el ajo, el pan escurrido, la sal y 500 ml de agua muy fría 3 minutos, hasta que quede muy fino.", 3),
      S("Añade el aceite en un hilo y el vinagre sin dejar de triturar. Ajusta de sal y de agua si lo quieres más ligero."),
      S("Enfría en la nevera al menos 1 hora y sirve con dados de manzana."),
    ],
  }),
  r({
    id: "potaje-de-vigilia", title: "Potaje de vigilia", cuisine: "espanola", authenticity: "traditional",
    origin: "España", note: "Plato de Cuaresma: garbanzos, espinacas y bacalao.",
    baseServings: 4, prepMin: 20, cookMin: 90, difficulty: "medium", equipment: ["olla", "sarten"],
    ingredients: [I("garbanzos", 300, "g"), I("bacalao", 250, "g"), I("espinacas", 300, "g"), I("huevo", 2, "unit"), I("ajo", 3, "unit"), I("pan", 30, "g"), I("pimenton", 4, "g"), I("aceite", 50, "ml"), I("sal", 4, "g")],
    steps: [
      S("La víspera, pon los garbanzos en remojo 12 horas."),
      S("Cuécelos en agua caliente a fuego suave 75 minutos (25 en olla a presión), hasta que estén tiernos.", 75),
      S("Fríe los ajos y el pan en el aceite 3 minutos y machácalos con el pimentón. Cuece los huevos 10 minutos.", 10),
      S("Añade al potaje el majado, las espinacas y el bacalao desmigado. Cocina 10 minutos más a fuego suave.", 10),
      S("Sirve con el huevo duro picado por encima."),
    ],
  }),
  r({
    id: "patatas-a-la-riojana", title: "Patatas a la riojana", cuisine: "espanola", authenticity: "traditional",
    origin: "España (La Rioja)", note: "La patata se «casca» (se rompe a medias con el cuchillo) para que suelte almidón y espese el caldo.",
    baseServings: 4, prepMin: 15, cookMin: 40, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("patata", 1000, "g"), I("chorizo", 200, "g"), I("cebolla", 1, "unit"), I("pimiento", 1, "unit"), I("ajo", 2, "unit"), I("pimenton", 5, "g"), I("aceite", 40, "ml"), I("sal", 6, "g"), I("chile", 1, "unit", true)],
    steps: [
      S("Pica la cebolla, el pimiento y el ajo y sofríelos en el aceite 10 minutos a fuego medio.", 10),
      S("Añade el chorizo en rodajas y cocina 3 minutos. Fuera del fuego, añade el pimentón y remueve 20 segundos.", 3),
      S("Pela las patatas y cáscalas en trozos. Añádelas a la olla y rehoga 2 minutos.", 2),
      S("Cubre con agua, sala y cocina a fuego medio-bajo 25 minutos, hasta que la patata esté tierna y el caldo espeso. Deja reposar 5 minutos.", 25),
    ],
  }),
  r({
    id: "pollo-en-pepitoria", title: "Pollo en pepitoria", cuisine: "espanola", authenticity: "adapted",
    origin: "España (Castilla)", note: "La receta clásica lleva azafrán; aquí se omite.",
    baseServings: 4, prepMin: 20, cookMin: 50, difficulty: "medium", equipment: ["olla", "batidora"],
    ingredients: [I("pollo", 1000, "g"), I("almendras", 50, "g"), I("huevo", 2, "unit"), I("ajo", 3, "unit"), I("cebolla", 1, "unit"), I("vino-blanco", 150, "ml"), I("caldo", 300, "ml"), I("harina", 20, "g"), I("aceite", 50, "ml"), I("perejil", 10, "g"), I("sal", 6, "g")],
    steps: [
      S("Cuece los huevos 10 minutos. Sala el pollo troceado y pásalo por harina.", 10),
      S("Dora el pollo en el aceite 10 minutos y resérvalo. En el mismo aceite, dora los ajos y las almendras 2 minutos y retíralos.", 12),
      S("Pocha la cebolla picada 8 minutos. Vuelve a poner el pollo, añade el vino y deja reducir 3 minutos. Agrega el caldo y cocina tapado 25 minutos.", 36),
      S("Tritura los ajos, las almendras, las yemas cocidas y el perejil con un poco de caldo. Añade el majado y cocina 5 minutos. Sirve con la clara picada.", 5),
    ],
  }),
  r({
    id: "berenjenas-con-miel", title: "Berenjenas fritas con miel", cuisine: "espanola", authenticity: "adapted",
    origin: "España (Andalucía)", note: "En Andalucía se usa miel de caña; con miel normal también quedan muy bien.",
    baseServings: 4, prepMin: 45, cookMin: 15, difficulty: "easy", equipment: ["sarten"],
    ingredients: [I("berenjena", 500, "g"), I("leche", 200, "ml"), I("harina", 100, "g"), I("miel", 60, "g"), I("aceite", 400, "ml"), I("sal", 5, "g")],
    steps: [
      S("Corta la berenjena en bastones o rodajas finas. Ponla en leche con sal 30 minutos: pierde el amargor y absorbe menos aceite.", 30),
      S("Escúrrela y pásala por harina, sacudiendo el exceso."),
      S("Fríe en el aceite a 180 °C en tandas pequeñas 2-3 minutos, hasta que estén doradas y crujientes.", 9, 180),
      S("Escúrrelas sobre papel, sala ligeramente y sirve enseguida con un hilo de miel por encima."),
    ],
  }),
  r({
    id: "ensalada-mixta", title: "Ensalada mixta", cuisine: "espanola", authenticity: "traditional",
    origin: "España", baseServings: 4, prepMin: 15, cookMin: 10, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("lechuga", 1, "unit"), I("tomate", 300, "g"), I("cebolla", 0.5, "unit"), I("atun-lata", 160, "g"), I("huevo", 2, "unit"), I("aceitunas", 50, "g"), I("maiz", 100, "g", true), I("aceite", 40, "ml"), I("vinagre", 15, "ml"), I("sal", 3, "g")],
    steps: [
      S("Cuece los huevos 10 minutos, enfríalos en agua y córtalos en cuartos.", 10),
      S("Lava y corta la lechuga, el tomate en gajos y la cebolla en aros finos."),
      S("Reparte en una fuente con el atún escurrido, los huevos, las aceitunas y el maíz."),
      S("Aliña justo antes de servir con sal, vinagre y aceite (por ese orden)."),
    ],
  }),
  r({
    id: "leche-frita", title: "Leche frita", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Castilla y León)", note: "La crema necesita enfriarse varias horas antes de cortarla.",
    baseServings: 6, prepMin: 20, cookMin: 25, difficulty: "medium", equipment: ["olla", "sarten"],
    ingredients: [I("leche", 750, "ml"), I("harina", 160, "g"), I("azucar", 120, "g"), I("huevo", 3, "unit"), I("canela", 5, "g"), I("limon", 1, "unit"), I("aceite", 400, "ml")],
    steps: [
      S("Calienta 600 ml de leche con la canela en rama y la piel del limón 5 minutos. Retíralas.", 5),
      S("Mezcla el resto de la leche fría con 110 g de harina, 100 g de azúcar y 2 yemas. Añádelo a la leche caliente y cocina removiendo 10 minutos, hasta que quede una crema muy espesa.", 10),
      S("Extiende en una fuente engrasada con 2 cm de grosor y deja enfriar en la nevera al menos 3 horas."),
      S("Corta en cuadrados, pásalos por harina y por huevo batido y fríelos a 180 °C 1 minuto por lado. Rebózalos en azúcar con canela molida.", 8, 180),
    ],
  }),
  // ——— Asturias ———
  r({
    id: "frixuelos", title: "Frixuelos", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Asturias)", note: "Primos asturianos de las crêpes. Se sirven con azúcar, miel o crema pastelera, sobre todo en Carnaval.",
    baseServings: 4, prepMin: 40, cookMin: 25, difficulty: "easy", equipment: ["sarten", "batidora"],
    ingredients: [I("harina", 125, "g"), I("huevo", 2, "unit"), I("leche", 300, "ml"), I("mantequilla", 20, "g"), I("azucar", 10, "g"), I("miel", 60, "g", true), I("sal", 1, "g")],
    steps: [
      S("Bate la harina, los huevos, la leche, el azúcar y la sal hasta una masa líquida y sin grumos. Deja reposar 30 minutos.", 30),
      S("Calienta una sartén pequeña a fuego medio y úntala con mantequilla."),
      S("Vierte un poco de masa, gira la sartén para cubrir el fondo y cocina 1 minuto. Dale la vuelta y cocina 30 segundos más.", 2),
      S("Repite con el resto de masa. Sírvelos doblados en cuatro, con azúcar o miel por encima."),
    ],
  }),
  r({
    id: "merluza-a-la-sidra", title: "Merluza a la sidra", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Asturias)", note: "Con sidra natural asturiana; la achampanada es demasiado dulce.",
    baseServings: 4, prepMin: 15, cookMin: 30, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("merluza", 600, "g"), I("almejas", 250, "g"), I("sidra", 300, "ml"), I("cebolla", 1, "unit"), I("ajo", 2, "unit"), I("harina", 10, "g"), I("patata", 400, "g"), I("aceite", 40, "ml"), I("perejil", 10, "g"), I("sal", 5, "g")],
    steps: [
      S("Corta las patatas en rodajas de 1 cm y cuécelas en agua con sal 12 minutos. Escúrrelas.", 12),
      S("Pocha la cebolla y el ajo picados en el aceite en una cazuela ancha 8 minutos. Añade la harina y remueve 1 minuto.", 9),
      S("Vierte la sidra y deja hervir 3 minutos para que pierda el alcohol.", 3),
      S("Coloca las patatas, la merluza salada y las almejas. Tapa y cocina 6 minutos hasta que las almejas se abran.", 6),
      S("Espolvorea perejil y sirve en la misma cazuela."),
    ],
  }),
  r({
    id: "carne-gobernada", title: "Carne gobernada", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Asturias)", note: "Guiso de ternera asturiano. Lo ideal es aguja o morcillo, cortes para guisar.",
    baseServings: 4, prepMin: 15, cookMin: 100, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("ternera", 800, "g"), I("cebolla", 2, "unit"), I("ajo", 3, "unit"), I("zanahoria", 150, "g"), I("vino-blanco", 200, "ml"), I("caldo", 300, "ml"), I("patata", 500, "g"), I("aceite", 50, "ml"), I("sal", 7, "g")],
    steps: [
      S("Corta la carne en dados de 4 cm y sálala. Dórala en el aceite a fuego fuerte en tandas, 6 minutos, y resérvala.", 6),
      S("En la misma olla, pocha las cebollas en juliana, el ajo y la zanahoria 12 minutos a fuego medio.", 12),
      S("Devuelve la carne, añade el vino y deja reducir 3 minutos. Agrega el caldo, tapa y cocina a fuego muy suave 70 minutos, hasta que la carne esté tierna.", 73),
      S("Fríe o cuece las patatas en dados y sírvelas con la carne y su salsa.", 10),
    ],
  }),
  r({
    id: "chorizo-a-la-sidra", title: "Chorizo a la sidra", cuisine: "espanola", authenticity: "traditional",
    origin: "España (Asturias)", note: "Clásico de sidrería. Mejor con chorizo asturiano ahumado.",
    baseServings: 4, prepMin: 5, cookMin: 25, difficulty: "easy", equipment: ["olla"],
    ingredients: [I("chorizo", 400, "g"), I("sidra", 500, "ml"), I("pan", 200, "g", true)],
    steps: [
      S("Pincha los chorizos con un tenedor para que no revienten y suelten la grasa."),
      S("Ponlos en una cazuela cubiertos de sidra y lleva a ebullición.", 5),
      S("Cocina a fuego medio 20 minutos, hasta que la sidra se reduzca a la mitad y tome color.", 20),
      S("Corta en rodajas gruesas y sirve en la cazuela con su salsa y pan para mojar."),
    ],
  }),
  r({
    id: "casadielles", title: "Casadielles", cuisine: "espanola", authenticity: "adapted",
    origin: "España (Asturias)", note: "Tradicionalmente se fríen y el relleno lleva anís; aquí se hornean.",
    baseServings: 6, prepMin: 25, cookMin: 20, difficulty: "medium", equipment: ["horno"],
    ingredients: [I("masa-hojaldre", 275, "g"), I("nueces", 150, "g"), I("azucar", 80, "g"), I("huevo", 1, "unit"), I("vino-blanco", 20, "ml")],
    steps: [
      S("Precalienta el horno a 190 °C. Pica las nueces muy finas y mézclalas con 60 g de azúcar y el vino hasta formar una pasta.", 10, 190),
      S("Corta la masa en rectángulos de 8 x 10 cm. Pon una tira de relleno en cada uno y enróllalos, cerrando bien los extremos."),
      S("Colócalas en la bandeja con papel, pinta con huevo batido y hornea 18 minutos hasta que estén doradas.", 18, 190),
      S("Espolvorea el resto del azúcar en caliente. Deja templar antes de comer."),
    ],
  }),
  // ——— Portugal ———
  r({
    id: "bacalhau-a-bras", title: "Bacalhau à brás", cuisine: "portuguesa", authenticity: "traditional",
    origin: "Portugal (Lisboa)", note: "Se usan patatas paja. Las de bolsa son un atajo aceptable.",
    baseServings: 4, prepMin: 20, cookMin: 25, difficulty: "medium", equipment: ["sarten"],
    ingredients: [I("bacalao", 400, "g"), I("patata", 500, "g"), I("huevo", 5, "unit"), I("cebolla", 1, "unit"), I("ajo", 2, "unit"), I("aceitunas", 50, "g"), I("perejil", 10, "g"), I("aceite", 350, "ml"), I("sal", 2, "g")],
    steps: [
      S("Corta las patatas en bastones muy finos (paja), lávalas, sécalas y fríelas en tandas a 180 °C 3 minutos, hasta que estén doradas.", 9, 180),
      S("Desmiga el bacalao en lascas. Pocha la cebolla en juliana y el ajo en 3 cucharadas de aceite 10 minutos.", 10),
      S("Añade el bacalao y cocina 3 minutos. Incorpora las patatas.", 3),
      S("Apaga el fuego, añade los huevos batidos y remueve 1 minuto con el calor residual: deben quedar cremosos.", 1),
      S("Sirve con perejil picado y aceitunas negras."),
    ],
  }),
  r({
    id: "caldo-verde", title: "Caldo verde", cuisine: "portuguesa", authenticity: "adapted",
    origin: "Portugal (Miño)", note: "Lleva col gallega (couve) cortada muy fina; aquí se usan espinacas.",
    baseServings: 4, prepMin: 15, cookMin: 35, difficulty: "easy", equipment: ["olla", "batidora"],
    ingredients: [I("patata", 600, "g"), I("chorizo", 150, "g"), I("espinacas", 200, "g"), I("cebolla", 1, "unit"), I("ajo", 2, "unit"), I("caldo", 1000, "ml"), I("aceite", 50, "ml"), I("sal", 5, "g")],
    steps: [
      S("Pocha la cebolla y el ajo picados en la mitad del aceite 6 minutos.", 6),
      S("Añade las patatas peladas en trozos y el caldo. Cocina 20 minutos hasta que estén muy tiernas.", 20),
      S("Tritura hasta obtener una crema fina. Dora el chorizo en rodajas en una sartén 3 minutos.", 3),
      S("Añade las espinacas cortadas en tiras finas a la crema y cocina 4 minutos.", 4),
      S("Sirve con el chorizo y un hilo de aceite crudo."),
    ],
  }),
  r({
    id: "frango-piri-piri", title: "Pollo piri-piri", cuisine: "portuguesa", authenticity: "adapted",
    origin: "Portugal (Algarve)", note: "En Portugal se hace a la brasa con guindilla piri-piri. Aquí, al horno.",
    baseServings: 4, prepMin: 75, cookMin: 50, difficulty: "easy", equipment: ["horno", "batidora"],
    ingredients: [I("pollo", 1000, "g"), I("chile", 4, "unit"), I("ajo", 4, "unit"), I("limon", 2, "unit"), I("pimenton", 6, "g"), I("vinagre", 30, "ml"), I("aceite", 50, "ml"), I("sal", 7, "g")],
    steps: [
      S("Tritura los chiles, el ajo, el zumo de un limón, el pimentón, el vinagre, el aceite y la sal hasta tener una salsa.", 2),
      S("Abre el pollo por la espalda (o usa muslos) y úntalo con la mitad de la salsa. Marina 1 hora en la nevera.", 60),
      S("Precalienta el horno a 210 °C y asa el pollo 45 minutos, pintándolo con más salsa a mitad. Está hecho cuando el jugo del muslo sale transparente.", 45, 210),
      S("Deja reposar 5 minutos y sirve con el limón restante y el resto de salsa aparte.", 5),
    ],
  }),
  r({
    id: "pasteis-de-nata", title: "Pastéis de nata", cuisine: "portuguesa", authenticity: "adapted",
    origin: "Portugal (Lisboa)", note: "Con hojaldre comprado y horno doméstico al máximo. Salen 12.",
    baseServings: 6, prepMin: 30, cookMin: 20, difficulty: "hard", equipment: ["horno", "olla"],
    ingredients: [I("masa-hojaldre", 275, "g"), I("leche", 250, "ml"), I("nata", 100, "ml"), I("huevo", 4, "unit"), I("azucar", 100, "g"), I("harina", 20, "g"), I("canela", 3, "g"), I("limon", 1, "unit")],
    steps: [
      S("Precalienta el horno a 250 °C (o al máximo). Enrolla el hojaldre, córtalo en 12 rodajas y aplasta cada una con los pulgares mojados en el fondo de un molde de magdalenas.", 15, 250),
      S("Calienta la leche con la canela, la piel de limón y el azúcar 5 minutos. Retira la canela y la piel.", 5),
      S("Mezcla las 4 yemas con la harina y la nata. Añade la leche caliente poco a poco y cocina a fuego bajo 3 minutos, removiendo, hasta que espese un poco.", 3),
      S("Llena los moldes hasta tres cuartos y hornea 12-15 minutos, hasta que la crema tenga manchas tostadas.", 14, 250),
      S("Deja templar y sirve con canela molida por encima."),
    ],
  }),
];
