// Generado por scripts/photo-download.mjs — no editar a mano.
// Fotos de Wikimedia Commons con licencia libre. Se muestran sin filtro, con su crédito.
export interface Photo { src: number; author: string; license: string; url: string }

export const PHOTOS: Record<string, Photo> = {
  "tortilla-de-patatas": { src: require("../../assets/photos/tortilla-de-patatas.jpg"), author: "Tamorlan", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Tortilla_de_Patatas_(Corte_transversal).jpg" },
  "pollo-al-ajillo": { src: require("../../assets/photos/pollo-al-ajillo.jpg"), author: "Juan Emilio Prades Bel", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pollo_al_ajillo.jpg" },
  "lentejas-con-chorizo": { src: require("../../assets/photos/lentejas-con-chorizo.jpg"), author: "Jonathan Pincas from Leon, Spain", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Quick_Lentils_with_Chorizo_(7017166123).jpg" },
  "garbanzos-con-espinacas": { src: require("../../assets/photos/garbanzos-con-espinacas.jpg"), author: "Toniher", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Potaje_de_vigilia.jpg" },
  "pollo-al-horno-con-arroz": { src: require("../../assets/photos/pollo-al-horno-con-arroz.jpg"), author: "MiguelAlanCS", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pollo_al_horno_Per%C3%BA.jpg" },
  "gambas-al-ajillo": { src: require("../../assets/photos/gambas-al-ajillo.jpg"), author: "Juan Emilio Prades Bel", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Las_gambas_al_ajillo,_t%C3%ADpica_tapa_espa%C3%B1ola.jpg" },
  "merluza-al-horno-con-patatas": { src: require("../../assets/photos/merluza-al-horno-con-patatas.jpg"), author: "El Pantera", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:MerluzaConBechamel-P1090667.JPG" },
  "huevos-rotos": { src: require("../../assets/photos/huevos-rotos.jpg"), author: "jlastras", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Huevos_rotos_con_jam%C3%B3n.jpg" },
  "sopa-de-ajo": { src: require("../../assets/photos/sopa-de-ajo.jpg"), author: "Xemenendura", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Sopa_Castellana_00.jpg" },
  "pisto-con-huevo": { src: require("../../assets/photos/pisto-con-huevo.jpg"), author: "El Mono Español", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pisto_manchego.jpg" },
  "fabada-asturiana": { src: require("../../assets/photos/fabada-asturiana.jpg"), author: "Amasuela, Luis Lafuente Agudín", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Fabada_con_compangu.jpg" },
  "espaguetis-al-pomodoro": { src: require("../../assets/photos/espaguetis-al-pomodoro.jpg"), author: "10Rosso", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_al_pomodoro_3.jpg" },
  "carbonara": { src: require("../../assets/photos/carbonara.jpg"), author: "Mattes Boch (Mboch on English Wikipedia)", license: "Public domain", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_alla_Carbonara.jpg" },
  "arroz-frito-con-huevo": { src: require("../../assets/photos/arroz-frito-con-huevo.jpg"), author: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Egg_Fried_Rice.jpg" },
  "chilaquiles-rojos": { src: require("../../assets/photos/chilaquiles-rojos.jpg"), author: "Pequeño mar", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Desayuno_mexicano.jpg" },
  "quesadillas": { src: require("../../assets/photos/quesadillas.jpg"), author: "Daderot", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chicken_quesadilla_-_Massachusetts.jpg" },
  "guacamole": { src: require("../../assets/photos/guacamole.jpg"), author: "Nikodem Nijaki", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Guacamole_IMGP1271.jpg" },
  "tacos-de-pollo": { src: require("../../assets/photos/tacos-de-pollo.jpg"), author: "Larry Miller", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:001_Tacos_de_carnitas,_carne_asada_y_al_pastor.jpg" },
  "pollo-al-curry": { src: require("../../assets/photos/pollo-al-curry.jpg"), author: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Chicken_Curry_with_Rice.jpg" },
  "dal-de-lentejas": { src: require("../../assets/photos/dal-de-lentejas.jpg"), author: "Soumendra Kumar Sahoo", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Rice_and_Dal_Makhni.jpg" },
  "karaage": { src: require("../../assets/photos/karaage.jpg"), author: "Ocdp", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chicken_karaage_003.jpg" },
  "oyakodon": { src: require("../../assets/photos/oyakodon.jpg"), author: "Ocdp", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Oyakodon_003.jpg" },
  "choripan-chimichurri": { src: require("../../assets/photos/choripan-chimichurri.jpg"), author: "Horacio Cambeiro", license: "CC BY 3.0", url: "https://commons.wikimedia.org/wiki/File:Chorip%C3%A1n_de_Argentina.jpg" },
  "calamares-fritos-yogur": { src: require("../../assets/photos/calamares-fritos-yogur.jpg"), author: "E4024", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Kalamar_tava_and_tartar_sauce.jpg" },
  "panang-pollo": { src: require("../../assets/photos/panang-pollo.jpg"), author: "Alpha from Melbourne, Australia", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Phanaeng_beef_curry.jpg" },
  "tallarines-verdes": { src: require("../../assets/photos/tallarines-verdes.jpg"), author: "Eduardo Vera-Palomino", license: "PDM-owner", url: "https://commons.wikimedia.org/wiki/File:Tallarines_verdes_huancaina.jpg" },
  "ensalada-griega": { src: require("../../assets/photos/ensalada-griega.jpg"), author: "cyclonebill", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Gr%C3%A6sk_salat.jpg" },
  "souvlaki-pollo-tzatziki": { src: require("../../assets/photos/souvlaki-pollo-tzatziki.jpg"), author: "StevenBjerke97", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Quebec_style_souvlaki_pita.jpg" },
  "bibimbap-casero": { src: require("../../assets/photos/bibimbap-casero.jpg"), author: "abex (a flickr user)", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Korean.food-Bibimbap-02.jpg" },
  "chana-masala": { src: require("../../assets/photos/chana-masala.jpg"), author: "Andy Li", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg" },
  "tajin-pollo-limon": { src: require("../../assets/photos/tajin-pollo-limon.jpg"), author: "Foodista", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Moroccan_food-Chicken_tagine_with_preserved_lemons_and_olives-01.jpg" },
  "risotto-champinones": { src: require("../../assets/photos/risotto-champinones.jpg"), author: "spurekar", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Mushroom_and_Leek_Risotto_(49535206656).jpg" },
  "pasta-aglio-olio": { src: require("../../assets/photos/pasta-aglio-olio.jpg"), author: "matsuyuki", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_aglio_olio_e_peperoncino_by_matsuyuki_retouched.jpg" },
  "shakshuka": { src: require("../../assets/photos/shakshuka.jpg"), author: "Calliopejen1", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Shakshuka_by_Calliopejen1.jpg" },
};
