// Generado por scripts/photo-download.mjs — no editar a mano.
// Fotos de Wikimedia Commons con licencia libre. Se muestran sin filtro, con su crédito.
export interface Photo { src: number; author: string; license: string; url: string }

export const PHOTOS: Record<string, Photo> = {
  "tortilla-de-patatas": { src: require("../../assets/photos/tortilla-de-patatas.jpg"), author: "Tamorlan", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Tortilla_de_Patatas_(Corte_transversal).jpg" },
  "pollo-al-ajillo": { src: require("../../assets/photos/pollo-al-ajillo.jpg"), author: "Juan Emilio Prades Bel", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pollo_al_ajillo.jpg" },
  "lentejas-con-chorizo": { src: require("../../assets/photos/lentejas-con-chorizo.jpg"), author: "Jonathan Pincas from Leon, Spain", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Quick_Lentils_with_Chorizo_(7017166123).jpg" },
  "garbanzos-con-espinacas": { src: require("../../assets/photos/garbanzos-con-espinacas.jpg"), author: "Toniher", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Potaje_de_vigilia.jpg" },
  "pollo-al-horno-con-arroz": { src: require("../../assets/photos/pollo-al-horno-con-arroz.jpg"), author: "MiguelAlanCS", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pollo_al_horno_Per%C3%BA.jpg" },
  "gambas-al-ajillo": { src: require("../../assets/photos/gambas-al-ajillo.jpg"), author: "Juan Emilio Prades Bel", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Las_gambas_al_ajillo,_t%C3%ADpica_tapa_espa%C3%B1ola.jpg" },
  "merluza-al-horno-con-patatas": { src: require("../../assets/photos/merluza-al-horno-con-patatas.jpg"), author: "El Pantera", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:MerluzaConBechamel-P1090667.JPG" },
  "huevos-rotos": { src: require("../../assets/photos/huevos-rotos.jpg"), author: "jlastras", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Huevos_rotos_con_jam%C3%B3n.jpg" },
  "sopa-de-ajo": { src: require("../../assets/photos/sopa-de-ajo.jpg"), author: "Xemenendura", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Sopa_Castellana_00.jpg" },
  "pisto-con-huevo": { src: require("../../assets/photos/pisto-con-huevo.jpg"), author: "El Mono Español", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pisto_manchego.jpg" },
  "fabada-asturiana": { src: require("../../assets/photos/fabada-asturiana.jpg"), author: "Amasuela, Luis Lafuente Agudín", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Fabada_con_compangu.jpg" },
  "espaguetis-al-pomodoro": { src: require("../../assets/photos/espaguetis-al-pomodoro.jpg"), author: "10Rosso", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_al_pomodoro_3.jpg" },
  "carbonara": { src: require("../../assets/photos/carbonara.jpg"), author: "Mattes Boch (Mboch on English Wikipedia)", license: "Public domain", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_alla_Carbonara.jpg" },
  "arroz-frito-con-huevo": { src: require("../../assets/photos/arroz-frito-con-huevo.jpg"), author: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Egg_Fried_Rice.jpg" },
  "chilaquiles-rojos": { src: require("../../assets/photos/chilaquiles-rojos.jpg"), author: "Pequeño mar", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Desayuno_mexicano.jpg" },
  "quesadillas": { src: require("../../assets/photos/quesadillas.jpg"), author: "Daderot", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chicken_quesadilla_-_Massachusetts.jpg" },
  "guacamole": { src: require("../../assets/photos/guacamole.jpg"), author: "Nikodem Nijaki", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Guacamole_IMGP1271.jpg" },
  "tacos-de-pollo": { src: require("../../assets/photos/tacos-de-pollo.jpg"), author: "Larry Miller", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:001_Tacos_de_carnitas,_carne_asada_y_al_pastor.jpg" },
  "pollo-al-curry": { src: require("../../assets/photos/pollo-al-curry.jpg"), author: "Gaurav Dhwaj Khadka", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Chicken_Curry_with_Rice.jpg" },
  "dal-de-lentejas": { src: require("../../assets/photos/dal-de-lentejas.jpg"), author: "Soumendra Kumar Sahoo", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Rice_and_Dal_Makhni.jpg" },
  "karaage": { src: require("../../assets/photos/karaage.jpg"), author: "Ocdp", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chicken_karaage_003.jpg" },
  "oyakodon": { src: require("../../assets/photos/oyakodon.jpg"), author: "Ocdp", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Oyakodon_003.jpg" },
  "choripan-chimichurri": { src: require("../../assets/photos/choripan-chimichurri.jpg"), author: "Horacio Cambeiro", license: "CC BY 3.0", url: "https://commons.wikimedia.org/wiki/File:Chorip%C3%A1n_de_Argentina.jpg" },
  "calamares-fritos-yogur": { src: require("../../assets/photos/calamares-fritos-yogur.jpg"), author: "E4024", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Kalamar_tava_and_tartar_sauce.jpg" },
  "panang-pollo": { src: require("../../assets/photos/panang-pollo.jpg"), author: "Alpha from Melbourne, Australia", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Phanaeng_beef_curry.jpg" },
  "tallarines-verdes": { src: require("../../assets/photos/tallarines-verdes.jpg"), author: "Eduardo Vera-Palomino", license: "PDM-owner", url: "https://commons.wikimedia.org/wiki/File:Tallarines_verdes_huancaina.jpg" },
  "ensalada-griega": { src: require("../../assets/photos/ensalada-griega.jpg"), author: "cyclonebill", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Flickr_-_cyclonebill_-_Gr%C3%A6sk_salat.jpg" },
  "souvlaki-pollo-tzatziki": { src: require("../../assets/photos/souvlaki-pollo-tzatziki.jpg"), author: "StevenBjerke97", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Quebec_style_souvlaki_pita.jpg" },
  "bibimbap-casero": { src: require("../../assets/photos/bibimbap-casero.jpg"), author: "abex (a flickr user)", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Korean.food-Bibimbap-02.jpg" },
  "chana-masala": { src: require("../../assets/photos/chana-masala.jpg"), author: "Andy Li", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chana_Masala_-_Mohammed_-_Spice_Of_Life_2024-05-27.jpg" },
  "tajin-pollo-limon": { src: require("../../assets/photos/tajin-pollo-limon.jpg"), author: "Foodista", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Moroccan_food-Chicken_tagine_with_preserved_lemons_and_olives-01.jpg" },
  "risotto-champinones": { src: require("../../assets/photos/risotto-champinones.jpg"), author: "spurekar", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Mushroom_and_Leek_Risotto_(49535206656).jpg" },
  "pasta-aglio-olio": { src: require("../../assets/photos/pasta-aglio-olio.jpg"), author: "matsuyuki", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_aglio_olio_e_peperoncino_by_matsuyuki_retouched.jpg" },
  "shakshuka": { src: require("../../assets/photos/shakshuka.jpg"), author: "Calliopejen1", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Shakshuka_by_Calliopejen1.jpg" },
  "paella-valenciana": { src: require("../../assets/photos/paella-valenciana.jpg"), author: "Wilfredor", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Paella_de_fruit_de_mer.jpg" },
  "gazpacho": { src: require("../../assets/photos/gazpacho.jpg"), author: "Bocadorada", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Gazpacho_Cazuela_Barro.jpg" },
  "patatas-bravas": { src: require("../../assets/photos/patatas-bravas.jpg"), author: "Francesc Fort", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Taberna_Che_-_Braves.jpg" },
  "albondigas-en-salsa": { src: require("../../assets/photos/albondigas-en-salsa.jpg"), author: "Juan Emilio Prades Bel", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Alb%C3%B3ndigas_en_salsa_con_patatas_fritas.jpg" },
  "cachopo": { src: require("../../assets/photos/cachopo.jpg"), author: "Kent Wang", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Cachopo,_KANTXA_Bera-Bera_01.jpg" },
  "arroz-con-leche": { src: require("../../assets/photos/arroz-con-leche.jpg"), author: "Juan Emilio Prades Bel", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Arroz_con_leche_espolvoreado_con_canela_molida.jpg" },
  "flan-de-huevo": { src: require("../../assets/photos/flan-de-huevo.jpg"), author: "Amanda Coutinho", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Cr%C3%A8me_caramel_2.jpg" },
  "espaguetis-bolonesa": { src: require("../../assets/photos/espaguetis-bolonesa.jpg"), author: "Triplec85", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Spaghetti_Bolognese_von_Unico_Tauberbischofsheim.jpg" },
  "pizza-margarita": { src: require("../../assets/photos/pizza-margarita.jpg"), author: "Mario56", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG" },
  "pasta-al-pesto": { src: require("../../assets/photos/pasta-al-pesto.jpg"), author: "Marco Del Torchio 95", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Pasta_al_pesto_fatto_in_casa.jpg" },
  "enchiladas-rojas": { src: require("../../assets/photos/enchiladas-rojas.jpg"), author: "Dahyana Yasada R. R.", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Enchiladas_con_salsa_roja.jpg" },
  "huevos-rancheros": { src: require("../../assets/photos/huevos-rancheros.jpg"), author: "1000b", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Huevos_rancheros.jpg" },
  "ramen-shoyu": { src: require("../../assets/photos/ramen-shoyu.jpg"), author: "Guilhem Vellut", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Shoyu_Ramen.jpg" },
  "pollo-teriyaki": { src: require("../../assets/photos/pollo-teriyaki.jpg"), author: "Daderot", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Chicken_teriyaki_bento_box_-_Massachusetts.jpg" },
  "gyudon": { src: require("../../assets/photos/gyudon.jpg"), author: "Ocdp", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Gyuu-don_001.jpg" },
  "pollo-kung-pao": { src: require("../../assets/photos/pollo-kung-pao.jpg"), author: "N509FZ", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Kung_Pao_Chicken_at_Yujiayan_Restaurant_(20230510123120).jpg" },
  "cerdo-agridulce": { src: require("../../assets/photos/cerdo-agridulce.jpg"), author: "Walter Grassroot", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:%E8%8F%A0%E8%90%9D%E5%92%95%E5%99%9C%E8%82%89.jpg" },
  "butter-chicken": { src: require("../../assets/photos/butter-chicken.jpg"), author: "stu_spivack", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Chicken_makhani.jpg" },
  "pad-thai": { src: require("../../assets/photos/pad-thai.jpg"), author: "Takeaway", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Phat_Thai_kung_Chang_Khien_street_stall.jpg" },
  "tom-kha-gai": { src: require("../../assets/photos/tom-kha-gai.jpg"), author: "lydiajoy1", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Tom_kha_gai2.jpg" },
  "banh-mi-cerdo": { src: require("../../assets/photos/banh-mi-cerdo.jpg"), author: "Bahnfrend", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Vietnamese_Grilled_Pork_B%C3%A1nh_M%C3%AC,_B%C3%A1nh_M%C3%AC_B%C3%A1nh_M%C3%AC_Westfield_Carousel,_2026_(01).jpg" },
  "bulgogi": { src: require("../../assets/photos/bulgogi.jpg"), author: "Guilhem Vellut from Paris, France", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Spicy_Pork_Bulgogi,_L%27Arbre_de_Sel,_Montparnasse,_Paris_001.jpg" },
  "ceviche": { src: require("../../assets/photos/ceviche.jpg"), author: "MINISTERIO DE LA PRODUCCIÓN - PRODUCE", license: "Public domain", url: "https://commons.wikimedia.org/wiki/File:Ceviche_peruano_es_inscrita_en_la_Lista_Representativa_de_Patrimonio_Cultural_Inmaterial_de_la_Humanidad_-_53381967964.jpg" },
  "lomo-saltado": { src: require("../../assets/photos/lomo-saltado.jpg"), author: "WikiHes", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Lomo-saltado-perudelights.jpg" },
  "empanadas-carne": { src: require("../../assets/photos/empanadas-carne.jpg"), author: "Tamorlan", license: "CC BY 3.0", url: "https://commons.wikimedia.org/wiki/File:Salte%C3%B1as_(Plaza_Mayor)-2011-01.JPG" },
  "milanesa": { src: require("../../assets/photos/milanesa.jpg"), author: "mteson Marcelo Teson Los Angeles, CA, USA", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Milanesa.jpg" },
  "moussaka": { src: require("../../assets/photos/moussaka.jpg"), author: "Andy Li", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Meat_Moussaka_-_Kouzina,_Brighton_2023-11-24.jpg" },
  "menemen": { src: require("../../assets/photos/menemen.jpg"), author: "E4024", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Menemen_in_a_sahan.jpg" },
  "kofte-yogur": { src: require("../../assets/photos/kofte-yogur.jpg"), author: "E4024", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Kofte_and_Pilav.jpg" },
  "harira": { src: require("../../assets/photos/harira.jpg"), author: "Miansari66", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Harira..JPG" },
  "hummus": { src: require("../../assets/photos/hummus.jpg"), author: "Paul Goyette", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Hummus_from_The_Nile.jpg" },
  "falafel": { src: require("../../assets/photos/falafel.jpg"), author: "Burkhard Mücke", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Falafel_beim_Isarinselfest_M%C3%BCnchen_2.jpg" },
  "crepes": { src: require("../../assets/photos/crepes.jpg"), author: "David Monniaux", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Crepes_dsc07085.jpg" },
  "ratatouille": { src: require("../../assets/photos/ratatouille.jpg"), author: "Arnaud 25", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Ratatouille_001.jpg" },
  "hamburguesa-casera": { src: require("../../assets/photos/hamburguesa-casera.jpg"), author: "Renee Comet (photographer)", license: "Public domain", url: "https://commons.wikimedia.org/wiki/File:Cheeseburger.jpg" },
  "mac-and-cheese": { src: require("../../assets/photos/mac-and-cheese.jpg"), author: "Stuart Spivack from Cleveland, Ohio, USA", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Flickr_stuart_spivack_173603796--Macaroni_and_cheese.jpg" },
  "moqueca": { src: require("../../assets/photos/moqueca.jpg"), author: "BR", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Moqueca.jpg" },
};
